
var Engine = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(moduleArg = {}) {

function f(){l.buffer!=n.buffer&&p();return n}function aa(){l.buffer!=n.buffer&&p();return ba}function u(){l.buffer!=n.buffer&&p();return ca}function w(){l.buffer!=n.buffer&&p();return da}function ea(){l.buffer!=n.buffer&&p();return fa}var x=moduleArg,ha,ia;x.ready=new Promise((a,b)=>{ha=a;ia=b});
var ja=Object.assign({},x),ka="./this.program",la=(a,b)=>{throw b;},ma="object"==typeof window,z="function"==typeof importScripts,na="object"==typeof process&&"object"==typeof process.rb&&"string"==typeof process.rb.node,B=x.ENVIRONMENT_IS_PTHREAD||!1,D="";function oa(a){return x.locateFile?x.locateFile(a,D):D+a}var pa;
if(ma||z)z?D=self.location.href:"undefined"!=typeof document&&document.currentScript&&(D=document.currentScript.src),_scriptDir&&(D=_scriptDir),0!==D.indexOf("blob:")?D=D.substr(0,D.replace(/[?#].*/,"").lastIndexOf("/")+1):D="",z&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var qa=x.print||console.log.bind(console),E=x.printErr||console.error.bind(console);Object.assign(x,ja);ja=null;x.thisProgram&&(ka=x.thisProgram);
x.quit&&(la=x.quit);var F;x.wasmBinary&&(F=x.wasmBinary);"object"!=typeof WebAssembly&&G("no native wasm support detected");var l,ra,sa=!1,I,n,ba,ca,da,fa;function p(){var a=l.buffer;x.HEAP8=n=new Int8Array(a);x.HEAP16=new Int16Array(a);x.HEAPU8=ba=new Uint8Array(a);x.HEAPU16=new Uint16Array(a);x.HEAP32=ca=new Int32Array(a);x.HEAPU32=da=new Uint32Array(a);x.HEAPF32=new Float32Array(a);x.HEAPF64=fa=new Float64Array(a)}var ta=x.INITIAL_MEMORY||629145600;
65536<=ta||G("INITIAL_MEMORY should be larger than STACK_SIZE, was "+ta+"! (STACK_SIZE=65536)");
if(B)l=x.wasmMemory;else if(x.wasmMemory)l=x.wasmMemory;else if(l=new WebAssembly.Memory({initial:ta/65536,maximum:32768,shared:!0}),!(l.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),na&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");p();ta=l.buffer.byteLength;var ua=[],va=[],wa=[],xa=[];function ya(){B||(x.noFSInit||za||(za=!0,Aa(),x.stdin=x.stdin,x.stdout=x.stdout,x.stderr=x.stderr,x.stdin?K("stdin",x.stdin):Ba("/dev/tty","/dev/stdin"),x.stdout?K("stdout",null,x.stdout):Ba("/dev/tty","/dev/stdout"),x.stderr?K("stderr",null,x.stderr):Ba("/dev/tty1","/dev/stderr"),Ca("/dev/stdin",0),Ca("/dev/stdout",1),Ca("/dev/stderr",1)),Da=!1,Ea(va))}var L=0,Fa=null,M=null;
function Ga(){L++;x.monitorRunDependencies&&x.monitorRunDependencies(L)}function Ha(){L--;x.monitorRunDependencies&&x.monitorRunDependencies(L);if(0==L&&(null!==Fa&&(clearInterval(Fa),Fa=null),M)){var a=M;M=null;a()}}function G(a){if(x.onAbort)x.onAbort(a);a="Aborted("+a+")";E(a);sa=!0;I=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ia(a);throw a;}var Ia=a=>a.startsWith("data:application/octet-stream;base64,"),N;
x.locateFile?(N="ChessEngine.wasm",Ia(N)||(N=oa(N))):N=(new URL("ChessEngine.wasm",import.meta.url)).href;function Ja(a){if(a==N&&F)return new Uint8Array(F);if(pa)return pa(a);throw"both async and sync fetching of the wasm failed";}function Ka(a){return F||!ma&&!z||"function"!=typeof fetch?Promise.resolve().then(()=>Ja(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ja(a))}
function La(a,b,c){return Ka(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{E(`failed to asynchronously prepare wasm: ${d}`);G(d)})}function Ma(a,b){var c=N;return F||"function"!=typeof WebAssembly.instantiateStreaming||Ia(c)||"function"!=typeof fetch?La(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){E(`wasm streaming compile failed: ${e}`);E("falling back to ArrayBuffer instantiation");return La(c,a,b)}))}var O,Na;
function Oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Pa=a=>{a.terminate();a.onmessage=()=>{}},Ra=a=>{0==Q.ka.length&&(Qa(),Q.Oa(Q.ka[0]));var b=Q.ka.pop();if(!b)return 6;Q.na.push(b);Q.fa[a.ma]=b;b.ma=a.ma;b.postMessage({cmd:"run",start_routine:a.jb,arg:a.bb,pthread_ptr:a.ma},a.pb);return 0},R=0,Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(d=>
!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Va=a=>{if("/"===a)return"/";a=Ta(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Wa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);G("initRandomDevice")},
Xa=a=>(Xa=Wa())(a);function Ya(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,S=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Za)return Za.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,d):a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else c+=String.fromCharCode(e)}return c},$a=[],ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},bb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var v=a.charCodeAt(++h);k=65536+((k&1023)<<10)|v&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+
3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e};function cb(a,b){var c=Array(ab(a)+1);a=bb(a,c,0,c.length);b&&(c.length=a);return c}var db=[];function eb(a,b){db[a]={input:[],ca:[],sa:b};fb(a,gb)}
var gb={open(a){var b=db[a.node.Aa];if(!b)throw new T(43);a.da=b;a.seekable=!1},close(a){a.da.sa.wa(a.da)},wa(a){a.da.sa.wa(a.da)},read(a,b,c,d){if(!a.da||!a.da.sa.Na)throw new T(60);for(var e=0,h=0;h<d;h++){try{var k=a.da.sa.Na(a.da)}catch(v){throw new T(29);}if(void 0===k&&0===e)throw new T(6);if(null===k||void 0===k)break;e++;b[c+h]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.da||!a.da.sa.Ga)throw new T(60);try{for(var e=0;e<d;e++)a.da.sa.Ga(a.da,b[c+e])}catch(h){throw new T(29);
}d&&(a.node.timestamp=Date.now());return e}},hb={Na(){a:{if(!$a.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}$a=cb(a,!0)}a=$a.shift()}return a},Ga(a,b){null===b||10===b?(qa(S(a.ca,0)),a.ca=[]):0!=b&&a.ca.push(b)},wa(a){a.ca&&0<a.ca.length&&(qa(S(a.ca,0)),a.ca=[])},Hb(){return{yb:25856,Ab:5,xb:191,zb:35387,wb:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ib(){return 0},Jb(){return[24,80]}},ib={Ga(a,b){null===b||10===b?(E(S(a.ca,0)),a.ca=[]):0!=b&&a.ca.push(b)},wa(a){a.ca&&0<a.ca.length&&(E(S(a.ca,0)),a.ca=[])}};function jb(a,b){var c=a.Z?a.Z.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Z,a.Z=new Uint8Array(b),0<a.ba&&a.Z.set(c.subarray(0,a.ba),0))}
var U={ea:null,ia(){return U.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.ea||(U.ea={dir:{node:{ja:U.$.ja,ga:U.$.ga,ta:U.$.ta,xa:U.$.xa,Ta:U.$.Ta,Za:U.$.Za,Va:U.$.Va,Sa:U.$.Sa,Ba:U.$.Ba},stream:{la:U.aa.la}},file:{node:{ja:U.$.ja,ga:U.$.ga},stream:{la:U.aa.la,read:U.aa.read,write:U.aa.write,Ja:U.aa.Ja,Pa:U.aa.Pa,Ra:U.aa.Ra}},link:{node:{ja:U.$.ja,ga:U.$.ga,ua:U.$.ua},stream:{}},Ka:{node:{ja:U.$.ja,ga:U.$.ga},stream:kb}});c=lb(a,b,c,d);
16384===(c.mode&61440)?(c.$=U.ea.dir.node,c.aa=U.ea.dir.stream,c.Z={}):32768===(c.mode&61440)?(c.$=U.ea.file.node,c.aa=U.ea.file.stream,c.ba=0,c.Z=null):40960===(c.mode&61440)?(c.$=U.ea.link.node,c.aa=U.ea.link.stream):8192===(c.mode&61440)&&(c.$=U.ea.Ka.node,c.aa=U.ea.Ka.stream);c.timestamp=Date.now();a&&(a.Z[b]=c,a.timestamp=c.timestamp);return c},Eb(a){return a.Z?a.Z.subarray?a.Z.subarray(0,a.ba):new Uint8Array(a.Z):new Uint8Array(0)},$:{ja(a){var b={};b.Db=8192===(a.mode&61440)?a.id:1;b.Gb=a.id;
b.mode=a.mode;b.Lb=1;b.uid=0;b.Fb=0;b.Aa=a.Aa;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ba:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ub=new Date(a.timestamp);b.Kb=new Date(a.timestamp);b.Cb=new Date(a.timestamp);b.cb=4096;b.vb=Math.ceil(b.size/b.cb);return b},ga(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ba!=b))if(0==b)a.Z=null,a.ba=0;else{var c=a.Z;a.Z=new Uint8Array(b);c&&a.Z.set(c.subarray(0,
Math.min(b,a.ba)));a.ba=b}},ta(){throw mb[44];},xa(a,b,c,d){return U.createNode(a,b,c,d)},Ta(a,b,c){if(16384===(a.mode&61440)){try{var d=nb(b,c)}catch(h){}if(d)for(var e in d.Z)throw new T(55);}delete a.parent.Z[a.name];a.parent.timestamp=Date.now();a.name=c;b.Z[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Za(a,b){delete a.Z[b];a.timestamp=Date.now()},Va(a,b){var c=nb(a,b),d;for(d in c.Z)throw new T(55);delete a.Z[b];a.timestamp=Date.now()},Sa(a){var b=[".",".."],c;for(c in a.Z)a.Z.hasOwnProperty(c)&&
b.push(c);return b},Ba(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},ua(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},aa:{read(a,b,c,d,e){var h=a.node.Z;if(e>=a.node.ba)return 0;a=Math.min(a.node.ba-e,d);if(8<a&&h.subarray)b.set(h.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=h[e+d];return a},write(a,b,c,d,e,h){b.buffer===f().buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Z||a.Z.subarray)){if(h)return a.Z=b.subarray(c,c+d),a.ba=d;if(0===a.ba&&
0===e)return a.Z=b.slice(c,c+d),a.ba=d;if(e+d<=a.ba)return a.Z.set(b.subarray(c,c+d),e),d}jb(a,e+d);if(a.Z.subarray&&b.subarray)a.Z.set(b.subarray(c,c+d),e);else for(h=0;h<d;h++)a.Z[e+h]=b[c+h];a.ba=Math.max(a.ba,e+d);return d},la(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ba);if(0>b)throw new T(28);return b},Ja(a,b,c){jb(a.node,b+c);a.node.ba=Math.max(a.node.ba,b+c)},Pa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.Z;if(e&2||a.buffer!==f().buffer){if(0<
c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;G();b=void 0;if(!b)throw new T(48);f().set(a,b)}else c=!1,b=a.byteOffset;return{za:b,tb:c}},Ra(a,b,c,d){U.aa.write(a,b,0,d,c,!1);return 0}}},ob=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},pb=null,qb={},rb=[],sb=1,V=null,Da=!0,T=null,mb={};
function W(a,b={}){a=Ya(a);if(!a)return{path:"",node:null};b=Object.assign({Ma:!0,Ha:0},b);if(8<b.Ha)throw new T(32);a=a.split("/").filter(k=>!!k);for(var c=pb,d="/",e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;c=nb(c,a[e]);d=Ta(d+"/"+a[e]);c.ya&&(!h||h&&b.Ma)&&(c=c.ya.root);if(!h||b.La)for(h=0;40960===(c.mode&61440);)if(c=tb(d),d=Ya(Ua(d),c),c=W(d,{Ha:b.Ha+1}).node,40<h++)throw new T(32);}return{path:d,node:c}}
function ub(a){for(var b;;){if(a===a.parent)return a=a.ia.Qa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%V.length}function nb(a,b){var c;if(c=(c=wb(a,"x"))?c:a.$.ta?0:2)throw new T(c,a);for(c=V[vb(a.id,b)];c;c=c.gb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$.ta(a,b)}
function lb(a,b,c,d){a=new xb(a,b,c,d);b=vb(a.parent.id,a.name);a.gb=V[b];return V[b]=a}function yb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function wb(a,b){if(Da)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function zb(a,b){try{return nb(a,b),20}catch(c){}return wb(a,"wx")}function Ab(){for(var a=0;4096>=a;a++)if(!rb[a])return a;throw new T(33);}
function Bb(a){a=rb[a];if(!a)throw new T(8);return a}function Cb(a){var b=-1;Db||(Db=function(){this.qa={}},Db.prototype={},Object.defineProperties(Db.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.qa.flags},set(c){this.qa.flags=c}},position:{get(){return this.qa.position},set(c){this.qa.position=c}}}));a=Object.assign(new Db,a);-1==b&&(b=Ab());a.ra=b;return rb[b]=a}var kb={open(a){a.aa=qb[a.node.Aa].aa;a.aa.open&&a.aa.open(a)},la(){throw new T(70);}};
function fb(a,b){qb[a]={aa:b}}function Eb(a,b){var c="/"===b,d=!b;if(c&&pb)throw new T(10);if(!c&&!d){var e=W(b,{Ma:!1});b=e.path;e=e.node;if(e.ya)throw new T(10);if(16384!==(e.mode&61440))throw new T(54);}b={type:a,Mb:{},Qa:b,fb:[]};a=a.ia(b);a.ia=b;b.root=a;c?pb=a:e&&(e.ya=b,e.ia&&e.ia.fb.push(b))}function Fb(a,b,c){var d=W(a,{parent:!0}).node;a=Va(a);if(!a||"."===a||".."===a)throw new T(28);var e=zb(d,a);if(e)throw new T(e);if(!d.$.xa)throw new T(63);return d.$.xa(d,a,b,c)}
function X(a){return Fb(a,16895,0)}function Gb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Fb(a,b|8192,c)}function Ba(a,b){if(!Ya(a))throw new T(44);var c=W(b,{parent:!0}).node;if(!c)throw new T(44);b=Va(b);var d=zb(c,b);if(d)throw new T(d);if(!c.$.Ba)throw new T(63);c.$.Ba(c,b,a)}function tb(a){a=W(a).node;if(!a)throw new T(44);if(!a.$.ua)throw new T(28);return Ya(ub(a.parent),a.$.ua(a))}
function Ca(a,b){if(""===a)throw new T(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}var d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ta(a);try{e=W(a,{La:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new T(20);}else e=Fb(a,d,0),c=!0;if(!e)throw new T(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new T(54);
if(!c&&(d=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==yb(b)||b&512)?31:wb(e,yb(b)):44))throw new T(d);if(b&512&&!c){d=e;d="string"==typeof d?W(d,{La:!0}).node:d;if(!d.$.ga)throw new T(63);if(16384===(d.mode&61440))throw new T(31);if(32768!==(d.mode&61440))throw new T(28);if(c=wb(d,"w"))throw new T(c);d.$.ga(d,{size:0,timestamp:Date.now()})}b&=-131713;e=Cb({node:e,path:ub(e),flags:b,seekable:!0,position:0,aa:e.aa,qb:[],error:!1});e.aa.open&&e.aa.open(e);!x.logReadFiles||b&1||(Hb||={},
a in Hb||(Hb[a]=1))}function Ib(a,b,c){if(null===a.ra)throw new T(8);if(!a.seekable||!a.aa.la)throw new T(70);if(0!=c&&1!=c&&2!=c)throw new T(28);a.position=a.aa.la(a,b,c);a.qb=[]}function Aa(){T||(T=function(a,b){this.name="ErrnoError";this.node=b;this.ib=function(c){this.va=c};this.ib(a);this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(a=>{mb[a]=new T(a);mb[a].stack="<generic error, no stack>"}))}var za;
function K(a,b,c){a=Ta("/dev/"+a);var d=ob(!!b,!!c);Jb||=64;var e=Jb++<<8|0;fb(e,{open(h){h.seekable=!1},close(){c&&c.buffer&&c.buffer.length&&c(10)},read(h,k,v,A){for(var m=0,r=0;r<A;r++){try{var C=b()}catch(H){throw new T(29);}if(void 0===C&&0===m)throw new T(6);if(null===C||void 0===C)break;m++;k[v+r]=C}m&&(h.node.timestamp=Date.now());return m},write(h,k,v,A){for(var m=0;m<A;m++)try{c(k[v+m])}catch(r){throw new T(29);}A&&(h.node.timestamp=Date.now());return m}});Gb(a,d,e)}
var Jb,Kb={},Db,Hb,Lb=a=>a?S(aa(),a):"",Ob=a=>{var b=Mb();a=a();Nb(b);return a};function Y(a,b){var c=arguments.length-2,d=arguments;return Ob(()=>{for(var e=Pb(8*c),h=e>>3,k=0;k<c;k++){var v=d[2+k];ea()[h+k]=v}return Qb(a,c,e,b)})}function Rb(a){if(B)return Y(0,1,a);I=a;if(!(Sb||0<R)){Q.kb();if(x.onExit)x.onExit(a);sa=!0}la(a,new Oa(a))}var Ub=a=>{I=a;if(B)throw Tb(a),"unwind";Rb(a)},Vb=a=>{a instanceof Oa||"unwind"==a||la(1,a)};
function Wb(){for(var a=8;a--;)Qa();ua.unshift(()=>{Ga();Xb(()=>Ha())})}function Qa(){if(x.locateFile){var a=oa("ChessEngine.worker.js");a=new Worker(a,{type:"module"})}else a=new Worker(new URL("ChessEngine.worker.js",import.meta.url),{type:"module"});Q.ka.push(a)}function Xb(a){B?a():Promise.all(Q.ka.map(Q.Oa)).then(a)}
var Q={ka:[],na:[],Ya:[],fa:{},Fa(){B?(Q.receiveObjectTransfer=Q.hb,Q.threadInitTLS=Q.Xa,Q.setExitStatus=Q.Wa,Sb=!1):Wb()},Wa:a=>{I=a},Nb:["$terminateWorker"],kb:()=>{for(var a of Q.na)Pa(a);for(a of Q.ka)Pa(a);Q.ka=[];Q.na=[];Q.fa=[]},Ua:a=>{var b=a.ma;delete Q.fa[b];Q.ka.push(a);Q.na.splice(Q.na.indexOf(a),1);a.ma=0;Yb(b)},hb(){},Xa(){Q.Ya.forEach(a=>a())},Oa:a=>new Promise(b=>{a.onmessage=h=>{h=h.data;var k=h.cmd;if(h.targetThread&&h.targetThread!=Zb()){var v=Q.fa[h.targetThread];v?v.postMessage(h,
h.transferList):E(`Internal error! Worker sent a message "${k}" to target pthread ${h.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===k)$b();else if("spawnThread"===k)Ra(h);else if("cleanupThread"===k)Q.Ua(Q.fa[h.thread]);else if("killThread"===k)h=h.thread,k=Q.fa[h],delete Q.fa[h],Pa(k),Yb(h),Q.na.splice(Q.na.indexOf(k),1),k.ma=0;else if("cancelThread"===k)Q.fa[h.thread].postMessage({cmd:"cancel"});else if("loaded"===k)a.loaded=!0,b(a);else if("alert"===k)alert(`Thread ${h.threadId}: ${h.text}`);
else if("setimmediate"===h.target)a.postMessage(h);else if("callHandler"===k)x[h.handler](...h.args);else k&&E(`worker sent an unknown command ${k}`)};a.onerror=h=>{E(`${"worker sent an error!"} ${h.filename}:${h.lineno}: ${h.message}`);throw h;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)x.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:x.mainScriptUrlOrBlob,wasmMemory:l,wasmModule:ra})})};x.PThread=Q;var Ea=a=>{for(;0<a.length;)a.shift()(x)};
x.establishStackSpace=()=>{var a=Zb(),b=w()[a+52>>2];a=w()[a+56>>2];ac(b,b-a);Nb(b)};function Tb(a){if(B)return Y(1,0,a);Ub(a)}var bc=[],cc;x.invokeEntryPoint=(a,b)=>{var c=bc[a];c||(a>=bc.length&&(bc.length=a+1),bc[a]=c=cc.get(a));a=c(b);Sb||0<R?Q.Wa(a):dc(a)};var Sb=x.noExitRuntime||!0;function ec(a){this.za=a-24;this.ab=function(b){w()[this.za+4>>2]=b};this.$a=function(b){w()[this.za+8>>2]=b};this.Fa=function(b,c){this.qa();this.ab(b);this.$a(c)};this.qa=function(){w()[this.za+16>>2]=0}}
var fc=0,gc=0;function hc(a,b,c,d){return B?Y(2,1,a,b,c,d):ic(a,b,c,d)}var ic=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(B&&0===e.length)return hc(a,b,c,d);a={jb:c,ma:a,bb:d,pb:e};return B?(a.Bb="spawnThread",postMessage(a,e),0):Ra(a)},jc=a=>{"function"===typeof Atomics.sb&&(Atomics.sb(u(),a>>2,a).value.then($b),a+=128,Atomics.store(u(),a>>2,1))};
x.__emscripten_thread_mailbox_await=jc;var $b=()=>{var a=Zb();if(a&&(jc(a),a=kc,!sa))try{if(a(),!(Sb||0<R))try{B?dc(I):Ub(I)}catch(b){Vb(b)}}catch(b){Vb(b)}};x.checkMailbox=$b;
var lc=[],mc={},oc=()=>{if(!nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ka||"./this.program"},b;for(b in mc)void 0===mc[b]?delete a[b]:a[b]=mc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nc=c}return nc},nc;
function pc(a,b){if(B)return Y(3,1,a,b);var c=0;oc().forEach((d,e)=>{var h=b+c;e=w()[a+4*e>>2]=h;for(h=0;h<d.length;++h)f()[e++>>0]=d.charCodeAt(h);f()[e>>0]=0;c+=d.length+1});return 0}function qc(a,b){if(B)return Y(4,1,a,b);var c=oc();w()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w()[b>>2]=d;return 0}
function rc(a){if(B)return Y(5,1,a);try{var b=Bb(a);if(null===b.ra)throw new T(8);b.Ea&&(b.Ea=null);try{b.aa.close&&b.aa.close(b)}catch(c){throw c;}finally{rb[b.ra]=null}b.ra=null;return 0}catch(c){if("undefined"==typeof Kb||"ErrnoError"!==c.name)throw c;return c.va}}
function sc(a,b,c,d){if(B)return Y(6,1,a,b,c,d);try{a:{var e=Bb(a);a=b;for(var h,k=b=0;k<c;k++){var v=w()[a>>2],A=w()[a+4>>2];a+=8;var m=e,r=f(),C=v,H=A,g=h;if(0>H||0>g)throw new T(28);if(null===m.ra)throw new T(8);if(1===(m.flags&2097155))throw new T(8);if(16384===(m.node.mode&61440))throw new T(31);if(!m.aa.read)throw new T(28);var q="undefined"!=typeof g;if(!q)g=m.position;else if(!m.seekable)throw new T(70);var t=m.aa.read(m,r,C,H,g);q||(m.position+=t);var y=t;if(0>y){var J=-1;break a}b+=y;if(y<
A)break;"undefined"!==typeof h&&(h+=y)}J=b}w()[d>>2]=J;return 0}catch(P){if("undefined"==typeof Kb||"ErrnoError"!==P.name)throw P;return P.va}}
function tc(a,b,c,d,e){if(B)return Y(7,1,a,b,c,d,e);b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var h=Bb(a);Ib(h,b,d);Na=[h.position>>>0,(O=h.position,1<=+Math.abs(O)?0<O?+Math.floor(O/4294967296)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];u()[e>>2]=Na[0];u()[e+4>>2]=Na[1];h.Ea&&0===b&&0===d&&(h.Ea=null);return 0}catch(k){if("undefined"==typeof Kb||"ErrnoError"!==k.name)throw k;return k.va}}
function uc(a,b,c,d){if(B)return Y(8,1,a,b,c,d);try{a:{var e=Bb(a);a=b;for(var h,k=b=0;k<c;k++){var v=w()[a>>2],A=w()[a+4>>2];a+=8;var m=e,r=f(),C=v,H=A,g=h;if(0>H||0>g)throw new T(28);if(null===m.ra)throw new T(8);if(0===(m.flags&2097155))throw new T(8);if(16384===(m.node.mode&61440))throw new T(31);if(!m.aa.write)throw new T(28);m.seekable&&m.flags&1024&&Ib(m,0,2);var q="undefined"!=typeof g;if(!q)g=m.position;else if(!m.seekable)throw new T(70);var t=m.aa.write(m,r,C,H,g,void 0);q||(m.position+=
t);var y=t;if(0>y){var J=-1;break a}b+=y;"undefined"!==typeof h&&(h+=y)}J=b}w()[d>>2]=J;return 0}catch(P){if("undefined"==typeof Kb||"ErrnoError"!==P.name)throw P;return P.va}}
var vc=a=>0===a%4&&(0!==a%100||0===a%400),wc=[31,29,31,30,31,30,31,31,30,31,30,31],xc=[31,28,31,30,31,30,31,31,30,31,30,31],yc=(a,b)=>{f().set(a,b)},zc=(a,b,c,d)=>{function e(g,q,t){for(g="number"==typeof g?g.toString():g||"";g.length<q;)g=t[0]+g;return g}function h(g,q){return e(g,q,"0")}function k(g,q){function t(J){return 0>J?-1:0<J?1:0}var y;0===(y=t(g.getFullYear()-q.getFullYear()))&&0===(y=t(g.getMonth()-q.getMonth()))&&(y=t(g.getDate()-q.getDate()));return y}function v(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-
1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function A(g){var q=g.oa;for(g=new Date((new Date(g.pa+1900,0,1)).getTime());0<q;){var t=g.getMonth(),y=(vc(g.getFullYear())?wc:xc)[t];if(q>y-g.getDate())q-=y-g.getDate()+1,g.setDate(1),11>t?g.setMonth(t+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+
1));else{g.setDate(g.getDate()+q);break}}t=new Date(g.getFullYear()+1,0,4);q=v(new Date(g.getFullYear(),0,4));t=v(t);return 0>=k(q,g)?0>=k(t,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var m=w()[d+40>>2];d={nb:u()[d>>2],mb:u()[d+4>>2],Ca:u()[d+8>>2],Ia:u()[d+12>>2],Da:u()[d+16>>2],pa:u()[d+20>>2],ha:u()[d+24>>2],oa:u()[d+28>>2],Ob:u()[d+32>>2],lb:u()[d+36>>2],ob:m?Lb(m):""};c=Lb(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M",
"%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in m)c=c.replace(new RegExp(r,"g"),m[r]);var C="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),H="January February March April May June July August September October November December".split(" ");m={"%a":g=>
C[g.ha].substring(0,3),"%A":g=>C[g.ha],"%b":g=>H[g.Da].substring(0,3),"%B":g=>H[g.Da],"%C":g=>h((g.pa+1900)/100|0,2),"%d":g=>h(g.Ia,2),"%e":g=>e(g.Ia,2," "),"%g":g=>A(g).toString().substring(2),"%G":g=>A(g),"%H":g=>h(g.Ca,2),"%I":g=>{g=g.Ca;0==g?g=12:12<g&&(g-=12);return h(g,2)},"%j":g=>{for(var q=0,t=0;t<=g.Da-1;q+=(vc(g.pa+1900)?wc:xc)[t++]);return h(g.Ia+q,3)},"%m":g=>h(g.Da+1,2),"%M":g=>h(g.mb,2),"%n":()=>"\n","%p":g=>0<=g.Ca&&12>g.Ca?"AM":"PM","%S":g=>h(g.nb,2),"%t":()=>"\t","%u":g=>g.ha||7,
"%U":g=>h(Math.floor((g.oa+7-g.ha)/7),2),"%V":g=>{var q=Math.floor((g.oa+7-(g.ha+6)%7)/7);2>=(g.ha+371-g.oa-2)%7&&q++;if(q)53==q&&(t=(g.ha+371-g.oa)%7,4==t||3==t&&vc(g.pa)||(q=1));else{q=52;var t=(g.ha+7-g.oa-1)%7;(4==t||5==t&&vc(g.pa%400-1))&&q++}return h(q,2)},"%w":g=>g.ha,"%W":g=>h(Math.floor((g.oa+7-(g.ha+6)%7)/7),2),"%y":g=>(g.pa+1900).toString().substring(2),"%Y":g=>g.pa+1900,"%z":g=>{g=g.lb;var q=0<=g;g=Math.abs(g)/60;return(q?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":g=>g.ob,
"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(r in m)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),m[r](d)));c=c.replace(/\0\0/g,"%");r=cb(c,!1);if(r.length>b)return 0;yc(r,a);return r.length-1},Ac=(a,b,c,d)=>{var e={string:m=>{var r=0;if(null!==m&&void 0!==m&&0!==m){r=ab(m)+1;var C=Pb(r);bb(m,aa(),C,r);r=C}return r},array:m=>{var r=Pb(m.length);f().set(m,r);return r}};a=x["_"+a];var h=[],k=0;if(d)for(var v=0;v<d.length;v++){var A=e[c[v]];A?(0===k&&(k=Mb()),h[v]=A(d[v])):h[v]=d[v]}c=a.apply(null,
h);return c=function(m){0!==k&&Nb(k);return"string"===b?Lb(m):"boolean"===b?!!m:m}(c)};Q.Fa();function xb(a,b,c,d){a||=this;this.parent=a;this.ia=a.ia;this.ya=null;this.id=sb++;this.name=b;this.mode=c;this.$={};this.aa={};this.Aa=d}Object.defineProperties(xb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Aa();V=Array(4096);
Eb(U,"/");X("/tmp");X("/home");X("/home/web_user");(function(){X("/dev");fb(259,{read:()=>0,write:(d,e,h,k)=>k});Gb("/dev/null",259);eb(1280,hb);eb(1536,ib);Gb("/dev/tty",1280);Gb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Xa(a).byteLength);return a[--b]};K("random",c);K("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Eb({ia(){var b=lb(a,"fd",16895,73);b.$={ta(c,d){var e=Bb(+d);c={parent:null,ia:{Qa:"fake"},$:{ua:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Bc=[Rb,Tb,hc,pc,qc,rc,sc,tc,uc],Dc={d:(a,b,c)=>{(new ec(a)).Fa(b,c);fc=a;gc++;throw fc;},j:a=>{Cc(a,!z,1,!ma,65536,!1);Q.Xa()},g:a=>{B?postMessage({cmd:"cleanupThread",thread:a}):Q.Ua(Q.fa[a])},x:ic,l:()=>!0,v:(a,b)=>{a==b?setTimeout(()=>$b()):B?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=Q.fa[a])&&a.postMessage({cmd:"checkMailbox"})},k:(a,b,c,d)=>{lc.length=c;d>>=3;for(var e=0;e<c;e++)lc[e]=ea()[d+e];a=Bc[a];Q.eb=b;b=a.apply(null,lc);Q.eb=0;return b},i:jc,h:()=>{},c:()=>{G("")},e:()=>
{},m:()=>Date.now(),y:()=>{R+=1;throw"unwind";},b:()=>performance.timeOrigin+performance.now(),u:a=>{var b=aa().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-l.buffer.byteLength+65535)/65536;try{l.grow(e);p();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},z:a=>{eval(Lb(a))},q:pc,r:qc,w:Ub,s:rc,t:sc,n:tc,f:uc,o:(a,b)=>{Xa(aa().subarray(a,a+b));
return 0},a:l||x.wasmMemory,p:(a,b,c,d)=>zc(a,b,c,d)},Z=function(){function a(c,d){Z=c.exports;Q.Ya.push(Z.N);cc=Z.M;va.unshift(Z.A);ra=d;Ha();return Z}var b={a:Dc};Ga();if(x.instantiateWasm)try{return x.instantiateWasm(b,a)}catch(c){E(`Module.instantiateWasm callback failed with error: ${c}`),ia(c)}Ma(b,function(c){a(c.instance,c.module)}).catch(ia);return{}}();x._init=()=>(x._init=Z.B)();x._move=(a,b,c,d,e)=>(x._move=Z.C)(a,b,c,d,e);x._unmove=()=>(x._unmove=Z.D)();
x._listPieces=()=>(x._listPieces=Z.E)();x._getMoves=()=>(x._getMoves=Z.F)();x._getAttacks=()=>(x._getAttacks=Z.G)();x._eval=()=>(x._eval=Z.H)();x._getBestMove=a=>(x._getBestMove=Z.I)(a);x._setFen=a=>(x._setFen=Z.J)(a);x._runPerft=(a,b)=>(x._runPerft=Z.K)(a,b);var Ec=x._main=(a,b)=>(Ec=x._main=Z.L)(a,b);x.__emscripten_tls_init=()=>(x.__emscripten_tls_init=Z.N)();
var Zb=x._pthread_self=()=>(Zb=x._pthread_self=Z.O)(),Cc=x.__emscripten_thread_init=(a,b,c,d,e,h)=>(Cc=x.__emscripten_thread_init=Z.P)(a,b,c,d,e,h);x.__emscripten_thread_crashed=()=>(x.__emscripten_thread_crashed=Z.Q)();var Qb=(a,b,c,d)=>(Qb=Z.R)(a,b,c,d),Yb=a=>(Yb=Z.S)(a),dc=x.__emscripten_thread_exit=a=>(dc=x.__emscripten_thread_exit=Z.T)(a),kc=()=>(kc=Z.U)(),ac=(a,b)=>(ac=Z.V)(a,b),Mb=()=>(Mb=Z.W)(),Nb=a=>(Nb=Z.X)(a),Pb=a=>(Pb=Z.Y)(a);x.wasmMemory=l;x.keepRuntimeAlive=()=>Sb||0<R;x.ccall=Ac;
x.cwrap=(a,b,c,d)=>{var e=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&e&&!d?x["_"+a]:function(){return Ac(a,b,c,arguments,d)}};x.ExitStatus=Oa;x.PThread=Q;var Fc;M=function Gc(){Fc||Hc();Fc||(M=Gc)};
function Hc(){function a(){if(!Fc&&(Fc=!0,x.calledRun=!0,!sa)){ya();B||Ea(wa);ha(x);if(x.onRuntimeInitialized)x.onRuntimeInitialized();if(Ic){var b=Ec;try{var c=b(0,0);Ub(c,!0)}catch(d){Vb(d)}}if(!B){if(x.postRun)for("function"==typeof x.postRun&&(x.postRun=[x.postRun]);x.postRun.length;)b=x.postRun.shift(),xa.unshift(b);Ea(xa)}}}if(!(0<L))if(B)ha(x),ya(),startWorker(x);else{if(x.preRun)for("function"==typeof x.preRun&&(x.preRun=[x.preRun]);x.preRun.length;)ua.unshift(x.preRun.shift());Ea(ua);0<L||
(x.setStatus?(x.setStatus("Running..."),setTimeout(function(){setTimeout(function(){x.setStatus("")},1);a()},1)):a())}}if(x.preInit)for("function"==typeof x.preInit&&(x.preInit=[x.preInit]);0<x.preInit.length;)x.preInit.pop()();var Ic=!0;x.noInitialRun&&(Ic=!1);Hc();


  return moduleArg.ready
}
);
})();
;
export default Engine;