
var Engine = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(moduleArg = {}) {

function g(){l.buffer!=q.buffer&&u();return q}function aa(){l.buffer!=q.buffer&&u();return ba}function ca(){l.buffer!=q.buffer&&u();return da}function w(){l.buffer!=q.buffer&&u();return ea}function y(){l.buffer!=q.buffer&&u();return fa}function ha(){l.buffer!=q.buffer&&u();return ia}var z=moduleArg,ja,ka;z.ready=new Promise((a,b)=>{ja=a;ka=b});
var la=Object.assign({},z),ma="./this.program",na=(a,b)=>{throw b;},oa="object"==typeof window,A="function"==typeof importScripts,pa="object"==typeof process&&"object"==typeof process.Jb&&"string"==typeof process.Jb.node,D=z.ENVIRONMENT_IS_PTHREAD||!1,E="";function qa(a){return z.locateFile?z.locateFile(a,E):E+a}var ra,sa,ta;
if(oa||A)A?E=self.location.href:"undefined"!=typeof document&&document.currentScript&&(E=document.currentScript.src),_scriptDir&&(E=_scriptDir),0!==E.indexOf("blob:")?E=E.substr(0,E.replace(/[?#].*/,"").lastIndexOf("/")+1):E="",ra=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},A&&(ta=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),sa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,
!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ua=z.print||console.log.bind(console),G=z.printErr||console.error.bind(console);Object.assign(z,la);la=null;z.thisProgram&&(ma=z.thisProgram);z.quit&&(na=z.quit);var va;z.wasmBinary&&(va=z.wasmBinary);"object"!=typeof WebAssembly&&H("no native wasm support detected");var l,wa,xa=!1,ya,q,ba,da,ea,fa,ia;
function u(){var a=l.buffer;z.HEAP8=q=new Int8Array(a);z.HEAP16=da=new Int16Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAP32=ea=new Int32Array(a);z.HEAPU32=fa=new Uint32Array(a);z.HEAPF32=new Float32Array(a);z.HEAPF64=ia=new Float64Array(a)}var za=z.INITIAL_MEMORY||629145600;65536<=za||H("INITIAL_MEMORY should be larger than STACK_SIZE, was "+za+"! (STACK_SIZE=65536)");
if(D)l=z.wasmMemory;else if(z.wasmMemory)l=z.wasmMemory;else if(l=new WebAssembly.Memory({initial:za/65536,maximum:32768,shared:!0}),!(l.buffer instanceof SharedArrayBuffer))throw G("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),pa&&G("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");u();za=l.buffer.byteLength;var Aa=[],Ba=[],Ca=[],Da=[];function Ea(){D||(z.noFSInit||Fa||(Fa=!0,Ga(),z.stdin=z.stdin,z.stdout=z.stdout,z.stderr=z.stderr,z.stdin?J("/dev","stdin",z.stdin):Ha("/dev/tty","/dev/stdin"),z.stdout?J("/dev","stdout",null,z.stdout):Ha("/dev/tty","/dev/stdout"),z.stderr?J("/dev","stderr",null,z.stderr):Ha("/dev/tty1","/dev/stderr"),Ia("/dev/stdin",0),Ia("/dev/stdout",1),Ia("/dev/stderr",1)),Ja=!1,Ka(Ba))}var K=0,La=null,Ma=null;
function Na(){K++;z.monitorRunDependencies&&z.monitorRunDependencies(K)}function Oa(){K--;z.monitorRunDependencies&&z.monitorRunDependencies(K);if(0==K&&(null!==La&&(clearInterval(La),La=null),Ma)){var a=Ma;Ma=null;a()}}function H(a){if(z.onAbort)z.onAbort(a);a="Aborted("+a+")";G(a);xa=!0;ya=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ka(a);throw a;}var Pa=a=>a.startsWith("data:application/octet-stream;base64,"),L;
z.locateFile?(L="ChessEngine.wasm",Pa(L)||(L=qa(L))):L=(new URL("ChessEngine.wasm",import.meta.url)).href;function Qa(a){if(a==L&&va)return new Uint8Array(va);if(ta)return ta(a);throw"both async and sync fetching of the wasm failed";}function Ra(a){return va||!oa&&!A||"function"!=typeof fetch?Promise.resolve().then(()=>Qa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Qa(a))}
function Sa(a,b,c){return Ra(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{G(`failed to asynchronously prepare wasm: ${d}`);H(d)})}function Ta(a,b){var c=L;return va||"function"!=typeof WebAssembly.instantiateStreaming||Pa(c)||"function"!=typeof fetch?Sa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){G(`wasm streaming compile failed: ${e}`);G("falling back to ArrayBuffer instantiation");return Sa(c,a,b)}))}
var Ua,Va,Wa={584040:a=>{postMessage({data:[N(a)],name:"log"})},584092:(a,b)=>{postMessage({data:[N(b)],name:N(a)})},584155:(a,b)=>{postMessage({data:[b],name:N(a)})}};function Xa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ya=a=>{a.terminate();a.onmessage=()=>{}},$a=a=>{0==O.ta.length&&(Za(),O.ab(O.ta[0]));var b=O.ta.pop();if(!b)return 6;O.wa.push(b);O.ma[a.va]=b;b.va=a.va;b.postMessage({cmd:"run",start_routine:a.Bb,arg:a.ob,pthread_ptr:a.va},a.Hb);return 0},ab=0,bb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},P=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(d=>
!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},cb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},db=a=>{if("/"===a)return"/";a=P(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},eb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);H("initRandomDevice")},
fb=a=>(fb=eb())(a);function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var hb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,ib=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&hb)return hb.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,d):a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else c+=String.fromCharCode(e)}return c},jb=[],kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},lb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var v=a.charCodeAt(++f);k=65536+((k&1023)<<10)|v&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+
3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e};function mb(a,b){var c=Array(kb(a)+1);a=lb(a,c,0,c.length);b&&(c.length=a);return c}var nb=[];function ob(a,b){nb[a]={input:[],ia:[],pa:b};pb(a,qb)}
var qb={open(a){var b=nb[a.node.Ha];if(!b)throw new Q(43);a.ga=b;a.seekable=!1},close(a){a.ga.pa.Da(a.ga)},Da(a){a.ga.pa.Da(a.ga)},read(a,b,c,d){if(!a.ga||!a.ga.pa.Za)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var k=a.ga.pa.Za(a.ga)}catch(v){throw new Q(29);}if(void 0===k&&0===e)throw new Q(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.ga||!a.ga.pa.Ra)throw new Q(60);try{for(var e=0;e<d;e++)a.ga.pa.Ra(a.ga,b[c+e])}catch(f){throw new Q(29);
}d&&(a.node.timestamp=Date.now());return e}},rb={Za(){a:{if(!jb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}jb=mb(a,!0)}a=jb.shift()}return a},Ra(a,b){null===b||10===b?(ua(ib(a.ia,0)),a.ia=[]):0!=b&&a.ia.push(b)},Da(a){a.ia&&0<a.ia.length&&(ua(ib(a.ia,0)),a.ia=[])},tb(){return{Qb:25856,Sb:5,Pb:191,Rb:35387,Ob:[3,28,127,21,4,0,1,
0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ub(){return 0},vb(){return[24,80]}},sb={Ra(a,b){null===b||10===b?(G(ib(a.ia,0)),a.ia=[]):0!=b&&a.ia.push(b)},Da(a){a.ia&&0<a.ia.length&&(G(ib(a.ia,0)),a.ia=[])}};function tb(a,b){var c=a.da?a.da.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.da,a.da=new Uint8Array(b),0<a.ha&&a.da.set(c.subarray(0,a.ha),0))}
var R={la:null,oa(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.la||(R.la={dir:{node:{sa:R.ea.sa,ja:R.ea.ja,Aa:R.ea.Aa,Fa:R.ea.Fa,gb:R.ea.gb,La:R.ea.La,ib:R.ea.ib,fb:R.ea.fb,Ia:R.ea.Ia},stream:{ua:R.fa.ua}},file:{node:{sa:R.ea.sa,ja:R.ea.ja},stream:{ua:R.fa.ua,read:R.fa.read,write:R.fa.write,Ua:R.fa.Ua,Qa:R.fa.Qa,eb:R.fa.eb}},link:{node:{sa:R.ea.sa,ja:R.ea.ja,Ca:R.ea.Ca},stream:{}},Wa:{node:{sa:R.ea.sa,ja:R.ea.ja},stream:ub}});
c=vb(a,b,c,d);16384===(c.mode&61440)?(c.ea=R.la.dir.node,c.fa=R.la.dir.stream,c.da={}):32768===(c.mode&61440)?(c.ea=R.la.file.node,c.fa=R.la.file.stream,c.ha=0,c.da=null):40960===(c.mode&61440)?(c.ea=R.la.link.node,c.fa=R.la.link.stream):8192===(c.mode&61440)&&(c.ea=R.la.Wa.node,c.fa=R.la.Wa.stream);c.timestamp=Date.now();a&&(a.da[b]=c,a.timestamp=c.timestamp);return c},Wb(a){return a.da?a.da.subarray?a.da.subarray(0,a.ha):new Uint8Array(a.da):new Uint8Array(0)},ea:{sa(a){var b={};b.Vb=8192===(a.mode&
61440)?a.id:1;b.Yb=a.id;b.mode=a.mode;b.$b=1;b.uid=0;b.Xb=0;b.Ha=a.Ha;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ha:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Mb=new Date(a.timestamp);b.Zb=new Date(a.timestamp);b.Ub=new Date(a.timestamp);b.pb=4096;b.Nb=Math.ceil(b.size/b.pb);return b},ja(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ha!=b))if(0==b)a.da=null,a.ha=0;else{var c=a.da;a.da=new Uint8Array(b);
c&&a.da.set(c.subarray(0,Math.min(b,a.ha)));a.ha=b}},Aa(){throw wb[44];},Fa(a,b,c,d){return R.createNode(a,b,c,d)},gb(a,b,c){if(16384===(a.mode&61440)){try{var d=xb(b,c)}catch(f){}if(d)for(var e in d.da)throw new Q(55);}delete a.parent.da[a.name];a.parent.timestamp=Date.now();a.name=c;b.da[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},La(a,b){delete a.da[b];a.timestamp=Date.now()},ib(a,b){var c=xb(a,b),d;for(d in c.da)throw new Q(55);delete a.da[b];a.timestamp=Date.now()},fb(a){var b=[".",".."],
c;for(c in a.da)a.da.hasOwnProperty(c)&&b.push(c);return b},Ia(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},Ca(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},fa:{read(a,b,c,d,e){var f=a.node.da;if(e>=a.node.ha)return 0;a=Math.min(a.node.ha-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.da||a.da.subarray)){if(f)return a.da=
b.subarray(c,c+d),a.ha=d;if(0===a.ha&&0===e)return a.da=b.slice(c,c+d),a.ha=d;if(e+d<=a.ha)return a.da.set(b.subarray(c,c+d),e),d}tb(a,e+d);if(a.da.subarray&&b.subarray)a.da.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.da[e+f]=b[c+f];a.ha=Math.max(a.ha,e+d);return d},ua(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ha);if(0>b)throw new Q(28);return b},Ua(a,b,c){tb(a.node,b+c);a.node.ha=Math.max(a.node.ha,b+c)},Qa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);
a=a.node.da;if(e&2||a.buffer!==g().buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;H();b=void 0;if(!b)throw new Q(48);g().set(a,b)}else c=!1,b=a.byteOffset;return{Ga:b,Lb:c}},eb(a,b,c,d){R.fa.write(a,b,0,d,c,!1);return 0}}},yb=(a,b,c)=>{var d=`al ${a}`;sa(a,e=>{e||H(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Oa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Na(d)},zb=z.preloadPlugins||[],
Ab=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Ea();var e=!1;zb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Cb=(a,b,c,d,e,f,k,v,x,n)=>{function m(h){function p(r){n&&n();v||Bb(a,b,r,d,e,x);f&&f();Oa(C)}Ab(h,t,p,()=>{k&&k();Oa(C)})||p(h)}var t=b?gb(P(a+"/"+b)):a,C=`cp ${t}`;Na(C);"string"==typeof c?yb(c,h=>m(h),k):m(c)},Db=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Eb=null,Fb={},Gb=[],Hb=1,S=null,Ja=!0,Q=null,wb={};
function T(a,b={}){a=gb(a);if(!a)return{path:"",node:null};b=Object.assign({Ya:!0,Sa:0},b);if(8<b.Sa)throw new Q(32);a=a.split("/").filter(k=>!!k);for(var c=Eb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=xb(c,a[e]);d=P(d+"/"+a[e]);c.Ba&&(!f||f&&b.Ya)&&(c=c.Ba.root);if(!f||b.Na)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=gb(cb(d),c),c=T(d,{Sa:b.Sa+1}).node,40<f++)throw new Q(32);}return{path:d,node:c}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.oa.cb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function xb(a,b){var c;if(c=(c=Lb(a,"x"))?c:a.ea.Aa?0:2)throw new Q(c,a);for(c=S[Kb(a.id,b)];c;c=c.za){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ea.Aa(a,b)}
function vb(a,b,c,d){a=new Mb(a,b,c,d);b=Kb(a.parent.id,a.name);a.za=S[b];return S[b]=a}function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Lb(a,b){if(Ja)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){try{return xb(a,b),20}catch(c){}return Lb(a,"wx")}function Pb(){for(var a=0;4096>=a;a++)if(!Gb[a])return a;throw new Q(33);}
function U(a){a=Gb[a];if(!a)throw new Q(8);return a}function Qb(a,b=-1){Rb||(Rb=function(){this.ka={}},Rb.prototype={},Object.defineProperties(Rb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ka.flags},set(c){this.ka.flags=c}},position:{get(){return this.ka.position},set(c){this.ka.position=c}}}));a=Object.assign(new Rb,a);-1==b&&(b=Pb());a.ra=b;return Gb[b]=a}var ub={open(a){a.fa=Fb[a.node.Ha].fa;a.fa.open&&a.fa.open(a)},ua(){throw new Q(70);}};
function pb(a,b){Fb[a]={fa:b}}function Sb(a,b){var c="/"===b,d=!b;if(c&&Eb)throw new Q(10);if(!c&&!d){var e=T(b,{Ya:!1});b=e.path;e=e.node;if(e.Ba)throw new Q(10);if(16384!==(e.mode&61440))throw new Q(54);}b={type:a,ac:{},cb:b,yb:[]};a=a.oa(b);a.oa=b;b.root=a;c?Eb=a:e&&(e.Ba=b,e.oa&&e.oa.yb.push(b))}function Tb(a,b,c){var d=T(a,{parent:!0}).node;a=db(a);if(!a||"."===a||".."===a)throw new Q(28);var e=Ob(d,a);if(e)throw new Q(e);if(!d.ea.Fa)throw new Q(63);return d.ea.Fa(d,a,b,c)}
function V(a){return Tb(a,16895,0)}function Ub(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Tb(a,b|8192,c)}function Ha(a,b){if(!gb(a))throw new Q(44);var c=T(b,{parent:!0}).node;if(!c)throw new Q(44);b=db(b);var d=Ob(c,b);if(d)throw new Q(d);if(!c.ea.Ia)throw new Q(63);c.ea.Ia(c,b,a)}
function Vb(a){var b=T(a,{parent:!0}).node;if(!b)throw new Q(44);var c=db(a);a=xb(b,c);a:{try{var d=xb(b,c)}catch(f){d=f.qa;break a}var e=Lb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new Q(d);if(!b.ea.La)throw new Q(63);if(a.Ba)throw new Q(10);b.ea.La(b,c);b=Kb(a.parent.id,a.name);if(S[b]===a)S[b]=a.za;else for(b=S[b];b;){if(b.za===a){b.za=a.za;break}b=b.za}}function Ib(a){a=T(a).node;if(!a)throw new Q(44);if(!a.ea.Ca)throw new Q(28);return gb(Jb(a.parent),a.ea.Ca(a))}
function Wb(a,b){a="string"==typeof a?T(a,{Na:!0}).node:a;if(!a.ea.ja)throw new Q(63);a.ea.ja(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ia(a,b,c){if(""===a)throw new Q(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=P(a);try{e=T(a,{Na:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new Q(20);}else e=Tb(a,c,0),d=!0;if(!e)throw new Q(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new Q(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Nb(b)||b&512)?31:Lb(e,Nb(b)):44))throw new Q(c);if(b&512&&!d){c=e;c="string"==typeof c?T(c,{Na:!0}).node:c;if(!c.ea.ja)throw new Q(63);if(16384===(c.mode&61440))throw new Q(31);if(32768!==(c.mode&61440))throw new Q(28);if(d=Lb(c,"w"))throw new Q(d);c.ea.ja(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Qb({node:e,path:Jb(e),flags:b,seekable:!0,position:0,fa:e.fa,Ib:[],error:!1});e.fa.open&&e.fa.open(e);!z.logReadFiles||b&1||(Xb||=
{},a in Xb||(Xb[a]=1));return e}function Yb(a){if(null===a.ra)throw new Q(8);a.Oa&&(a.Oa=null);try{a.fa.close&&a.fa.close(a)}catch(b){throw b;}finally{Gb[a.ra]=null}a.ra=null}function Zb(a,b,c){if(null===a.ra)throw new Q(8);if(!a.seekable||!a.fa.ua)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.fa.ua(a,b,c);a.Ib=[]}
function $b(a,b,c,d,e,f){if(0>d||0>e)throw new Q(28);if(null===a.ra)throw new Q(8);if(0===(a.flags&2097155))throw new Q(8);if(16384===(a.node.mode&61440))throw new Q(31);if(!a.fa.write)throw new Q(28);a.seekable&&a.flags&1024&&Zb(a,0,2);var k="undefined"!=typeof e;if(!k)e=a.position;else if(!a.seekable)throw new Q(70);b=a.fa.write(a,b,c,d,e,f);k||(a.position+=b);return b}
function Ga(){Q||(Q=function(a,b){this.name="ErrnoError";this.node=b;this.Ab=function(c){this.qa=c};this.Ab(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(a=>{wb[a]=new Q(a);wb[a].stack="<generic error, no stack>"}))}var Fa;function ac(a,b){a="string"==typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=P(a+"/"+c);try{V(d)}catch(e){}a=d}}return d}
function bc(a,b,c,d){a=P(("string"==typeof a?a:Jb(a))+"/"+b);c=Db(c,d);return Tb(a,(void 0!==c?c:438)&4095|32768,0)}function Bb(a,b,c,d,e,f){var k=b;a&&(a="string"==typeof a?a:Jb(a),k=b?P(a+"/"+b):a);a=Db(d,e);k=Tb(k,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Wb(k,a|146);b=Ia(k,577);$b(b,c,0,c.length,0,f);Yb(b);Wb(k,a)}}
function J(a,b,c,d){a=P(("string"==typeof a?a:Jb(a))+"/"+b);b=Db(!!c,!!d);J.bb||(J.bb=64);var e=J.bb++<<8|0;pb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,k,v,x){for(var n=0,m=0;m<x;m++){try{var t=c()}catch(C){throw new Q(29);}if(void 0===t&&0===n)throw new Q(6);if(null===t||void 0===t)break;n++;k[v+m]=t}n&&(f.node.timestamp=Date.now());return n},write(f,k,v,x){for(var n=0;n<x;n++)try{d(k[v+n])}catch(m){throw new Q(29);}x&&(f.node.timestamp=Date.now());return n}});
return Ub(a,b,e)}function cc(a){if(!(a.wb||a.xb||a.link||a.da)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ra)try{a.da=mb(ra(a.url),!0),a.ha=a.da.length}catch(b){throw new Q(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function dc(a,b,c,d,e){function f(){this.Pa=!1;this.ka=[]}f.prototype.get=function(m){if(!(m>this.length-1||0>m)){var t=m%this.Xa;return this.$a(m/this.Xa|0)[t]}};f.prototype.Ma=function(m){this.$a=m};f.prototype.Va=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var t=Number(m.getResponseHeader("Content-length")),C,h=(C=m.getResponseHeader("Accept-Ranges"))&&"bytes"===C;m=
(C=m.getResponseHeader("Content-Encoding"))&&"gzip"===C;var p=1048576;h||(p=t);var r=this;r.Ma(B=>{var I=B*p,M=(B+1)*p-1;M=Math.min(M,t-1);if("undefined"==typeof r.ka[B]){var Yc=r.ka;if(I>M)throw Error("invalid range ("+I+", "+M+") or no bytes requested!");if(M>t-1)throw Error("only "+t+" bytes available! programmer error!");var F=new XMLHttpRequest;F.open("GET",c,!1);t!==p&&F.setRequestHeader("Range","bytes="+I+"-"+M);F.responseType="arraybuffer";F.overrideMimeType&&F.overrideMimeType("text/plain; charset=x-user-defined");
F.send(null);if(!(200<=F.status&&300>F.status||304===F.status))throw Error("Couldn't load "+c+". Status: "+F.status);I=void 0!==F.response?new Uint8Array(F.response||[]):mb(F.responseText||"",!0);Yc[B]=I}if("undefined"==typeof r.ka[B])throw Error("doXHR failed!");return r.ka[B]});if(m||!t)p=t=1,p=t=this.$a(0).length,ua("LazyFiles on gzip forces download of the whole file when length is accessed");this.nb=t;this.mb=p;this.Pa=!0};if("undefined"!=typeof XMLHttpRequest){if(!A)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var k=new f;Object.defineProperties(k,{length:{get:function(){this.Pa||this.Va();return this.nb}},Xa:{get:function(){this.Pa||this.Va();return this.mb}}});var v=void 0}else v=c,k=void 0;var x=bc(a,b,d,e);k?x.da=k:v&&(x.da=null,x.url=v);Object.defineProperties(x,{ha:{get:function(){return this.da.length}}});var n={};Object.keys(x.fa).forEach(m=>{var t=x.fa[m];n[m]=function(){cc(x);return t.apply(null,arguments)}});n.read=(m,t,C,h,p)=>{cc(x);m=m.node.da;if(p>=m.length)t=0;else{h=Math.min(m.length-p,
h);if(m.slice)for(var r=0;r<h;r++)t[C+r]=m[p+r];else for(r=0;r<h;r++)t[C+r]=m.get(p+r);t=h}return t};n.Qa=()=>{cc(x);H();throw new Q(48);};x.fa=n;return x}var W={},Rb,Xb,N=a=>a?ib(aa(),a):"",ec=void 0;function X(){var a=w()[+ec>>2];ec+=4;return a}var hc=a=>{var b=fc();a=a();gc(b);return a};function Y(a,b){var c=arguments.length-2,d=arguments;return hc(()=>{for(var e=ic(8*c),f=e>>3,k=0;k<c;k++){var v=d[2+k];ha()[f+k]=v}return jc(a,c,e,b)})}
function kc(a){if(D)return Y(0,1,a);ya=a;if(!(lc||0<ab)){O.Cb();if(z.onExit)z.onExit(a);xa=!0}na(a,new Xa(a))}var nc=a=>{ya=a;if(D)throw mc(a),"unwind";kc(a)},oc=a=>{a instanceof Xa||"unwind"==a||na(1,a)};function pc(){for(var a=8;a--;)Za();Aa.unshift(()=>{Na("loading-workers");qc(()=>Oa("loading-workers"))})}
function Za(){if(z.locateFile){var a=qa("ChessEngine.worker.js");a=new Worker(a,{type:"module"})}else a=new Worker(new URL("ChessEngine.worker.js",import.meta.url),{type:"module"});O.ta.push(a)}function qc(a){D?a():Promise.all(O.ta.map(O.ab)).then(a)}
var O={ta:[],wa:[],lb:[],ma:{},Ea(){D?(O.receiveObjectTransfer=O.zb,O.threadInitTLS=O.kb,O.setExitStatus=O.jb,lc=!1):pc()},jb:a=>{ya=a},bc:["$terminateWorker"],Cb:()=>{for(var a of O.wa)Ya(a);for(a of O.ta)Ya(a);O.ta=[];O.wa=[];O.ma=[]},hb:a=>{var b=a.va;delete O.ma[b];O.ta.push(a);O.wa.splice(O.wa.indexOf(a),1);a.va=0;rc(b)},zb(){},kb(){O.lb.forEach(a=>a())},ab:a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var k=f.cmd;if(f.targetThread&&f.targetThread!=sc()){var v=O.ma[f.targetThread];v?v.postMessage(f,
f.transferList):G(`Internal error! Worker sent a message "${k}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===k)tc();else if("spawnThread"===k)$a(f);else if("cleanupThread"===k)O.hb(O.ma[f.thread]);else if("killThread"===k)f=f.thread,k=O.ma[f],delete O.ma[f],Ya(k),rc(f),O.wa.splice(O.wa.indexOf(k),1),k.va=0;else if("cancelThread"===k)O.ma[f.thread].postMessage({cmd:"cancel"});else if("loaded"===k)a.loaded=!0,b(a);else if("alert"===k)alert(`Thread ${f.threadId}: ${f.text}`);
else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===k)z[f.handler](...f.args);else k&&G(`worker sent an unknown command ${k}`)};a.onerror=f=>{G(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)z.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:z.mainScriptUrlOrBlob,wasmMemory:l,wasmModule:wa})})};z.PThread=O;var Ka=a=>{for(;0<a.length;)a.shift()(z)};
z.establishStackSpace=()=>{var a=sc(),b=y()[a+52>>2];a=y()[a+56>>2];uc(b,b-a);gc(b)};function mc(a){if(D)return Y(1,0,a);nc(a)}var vc=[],wc;z.invokeEntryPoint=(a,b)=>{var c=vc[a];c||(a>=vc.length&&(vc.length=a+1),vc[a]=c=wc.get(a));a=c(b);lc||0<ab?O.jb(a):xc(a)};var lc=z.noExitRuntime||!0;function yc(a){this.Ga=a-24;this.rb=function(b){y()[this.Ga+4>>2]=b};this.Ma=function(b){y()[this.Ga+8>>2]=b};this.Ea=function(b,c){this.ka();this.rb(b);this.Ma(c)};this.ka=function(){y()[this.Ga+16>>2]=0}}
var zc=0,Ac=0;function Bc(a,b,c,d){return D?Y(2,1,a,b,c,d):Cc(a,b,c,d)}var Cc=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return G("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(D&&0===e.length)return Bc(a,b,c,d);a={Bb:c,va:a,ob:d,Hb:e};return D?(a.Tb="spawnThread",postMessage(a,e),0):$a(a)};
function Dc(a,b,c){if(D)return Y(3,1,a,b,c);ec=c;try{var d=U(a);switch(b){case 0:var e=X();if(0>e)return-28;for(;Gb[e];)e++;return Qb(d,e).ra;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=X(),d.flags|=e,0;case 5:return e=X(),ca()[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return w()[Ec()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.qa}}
function Fc(a,b,c){if(D)return Y(4,1,a,b,c);ec=c;try{var d=U(a);switch(b){case 21509:return d.ga?0:-59;case 21505:if(!d.ga)return-59;if(d.ga.pa.tb){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=X();w()[e>>2]=25856;w()[e+4>>2]=5;w()[e+8>>2]=191;w()[e+12>>2]=35387;for(var f=0;32>f;f++)g()[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.ga?0:-59;case 21506:case 21507:case 21508:if(!d.ga)return-59;if(d.ga.pa.ub)for(e=X(),w(),w(),w(),w(),b=[],
f=0;32>f;f++)b.push(g()[e+f+17>>0]);return 0;case 21519:if(!d.ga)return-59;e=X();return w()[e>>2]=0;case 21520:return d.ga?-28:-59;case 21531:e=X();if(!d.fa.sb)throw new Q(59);return d.fa.sb(d,b,e);case 21523:if(!d.ga)return-59;d.ga.pa.vb&&(f=[24,80],e=X(),ca()[e>>1]=f[0],ca()[e+2>>1]=f[1]);return 0;case 21524:return d.ga?0:-59;case 21515:return d.ga?0:-59;default:return-28}}catch(k){if("undefined"==typeof W||"ErrnoError"!==k.name)throw k;return-k.qa}}
function Gc(a,b,c,d){if(D)return Y(5,1,a,b,c,d);ec=d;try{b=N(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":U(a).path;if(0==e.length)throw new Q(44);b=P(f+"/"+e)}var k=d?X():0;return Ia(b,c,k).ra}catch(v){if("undefined"==typeof W||"ErrnoError"!==v.name)throw v;return-v.qa}}var Hc=a=>{"function"===typeof Atomics.Kb&&(Atomics.Kb(w(),a>>2,a).value.then(tc),a+=128,Atomics.store(w(),a>>2,1))};z.__emscripten_thread_mailbox_await=Hc;
var tc=()=>{var a=sc();if(a&&(Hc(a),a=Ic,!xa))try{if(a(),!(lc||0<ab))try{D?xc(ya):nc(ya)}catch(b){oc(b)}}catch(b){oc(b)}};z.checkMailbox=tc;
var Jc=[],Kc=[],Lc={},Nc=()=>{if(!Mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ma||"./this.program"},b;for(b in Lc)void 0===Lc[b]?delete a[b]:a[b]=Lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Mc=c}return Mc},Mc;
function Oc(a,b){if(D)return Y(6,1,a,b);var c=0;Nc().forEach((d,e)=>{var f=b+c;e=y()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function Pc(a,b){if(D)return Y(7,1,a,b);var c=Nc();y()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);y()[b>>2]=d;return 0}function Qc(a){if(D)return Y(8,1,a);try{var b=U(a);Yb(b);return 0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.qa}}
function Rc(a,b,c,d){if(D)return Y(9,1,a,b,c,d);try{a:{var e=U(a);a=b;for(var f,k=b=0;k<c;k++){var v=y()[a>>2],x=y()[a+4>>2];a+=8;var n=e,m=g(),t=v,C=x,h=f;if(0>C||0>h)throw new Q(28);if(null===n.ra)throw new Q(8);if(1===(n.flags&2097155))throw new Q(8);if(16384===(n.node.mode&61440))throw new Q(31);if(!n.fa.read)throw new Q(28);var p="undefined"!=typeof h;if(!p)h=n.position;else if(!n.seekable)throw new Q(70);var r=n.fa.read(n,m,t,C,h);p||(n.position+=r);var B=r;if(0>B){var I=-1;break a}b+=B;if(B<
x)break;"undefined"!==typeof f&&(f+=B)}I=b}y()[d>>2]=I;return 0}catch(M){if("undefined"==typeof W||"ErrnoError"!==M.name)throw M;return M.qa}}
function Sc(a,b,c,d,e){if(D)return Y(10,1,a,b,c,d,e);b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=U(a);Zb(f,b,d);Va=[f.position>>>0,(Ua=f.position,1<=+Math.abs(Ua)?0<Ua?+Math.floor(Ua/4294967296)>>>0:~~+Math.ceil((Ua-+(~~Ua>>>0))/4294967296)>>>0:0)];w()[e>>2]=Va[0];w()[e+4>>2]=Va[1];f.Oa&&0===b&&0===d&&(f.Oa=null);return 0}catch(k){if("undefined"==typeof W||"ErrnoError"!==k.name)throw k;return k.qa}}
function Tc(a,b,c,d){if(D)return Y(11,1,a,b,c,d);try{a:{var e=U(a);a=b;for(var f,k=b=0;k<c;k++){var v=y()[a>>2],x=y()[a+4>>2];a+=8;var n=$b(e,g(),v,x,f);if(0>n){var m=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}m=b}y()[d>>2]=m;return 0}catch(t){if("undefined"==typeof W||"ErrnoError"!==t.name)throw t;return t.qa}}
var Uc=a=>0===a%4&&(0!==a%100||0===a%400),Vc=[31,29,31,30,31,30,31,31,30,31,30,31],Wc=[31,28,31,30,31,30,31,31,30,31,30,31],Xc=(a,b)=>{g().set(a,b)},Zc=(a,b,c,d)=>{function e(h,p,r){for(h="number"==typeof h?h.toString():h||"";h.length<p;)h=r[0]+h;return h}function f(h,p){return e(h,p,"0")}function k(h,p){function r(I){return 0>I?-1:0<I?1:0}var B;0===(B=r(h.getFullYear()-p.getFullYear()))&&0===(B=r(h.getMonth()-p.getMonth()))&&(B=r(h.getDate()-p.getDate()));return B}function v(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-
1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function x(h){var p=h.xa;for(h=new Date((new Date(h.ya+1900,0,1)).getTime());0<p;){var r=h.getMonth(),B=(Uc(h.getFullYear())?Vc:Wc)[r];if(p>B-h.getDate())p-=B-h.getDate()+1,h.setDate(1),11>r?h.setMonth(r+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+
1));else{h.setDate(h.getDate()+p);break}}r=new Date(h.getFullYear()+1,0,4);p=v(new Date(h.getFullYear(),0,4));r=v(r);return 0>=k(p,h)?0>=k(r,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=y()[d+40>>2];d={Fb:w()[d>>2],Eb:w()[d+4>>2],Ja:w()[d+8>>2],Ta:w()[d+12>>2],Ka:w()[d+16>>2],ya:w()[d+20>>2],na:w()[d+24>>2],xa:w()[d+28>>2],cc:w()[d+32>>2],Db:w()[d+36>>2],Gb:n?N(n):""};c=N(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var m in n)c=c.replace(new RegExp(m,"g"),n[m]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),C="January February March April May June July August September October November December".split(" ");n={"%a":h=>t[h.na].substring(0,
3),"%A":h=>t[h.na],"%b":h=>C[h.Ka].substring(0,3),"%B":h=>C[h.Ka],"%C":h=>f((h.ya+1900)/100|0,2),"%d":h=>f(h.Ta,2),"%e":h=>e(h.Ta,2," "),"%g":h=>x(h).toString().substring(2),"%G":h=>x(h),"%H":h=>f(h.Ja,2),"%I":h=>{h=h.Ja;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":h=>{for(var p=0,r=0;r<=h.Ka-1;p+=(Uc(h.ya+1900)?Vc:Wc)[r++]);return f(h.Ta+p,3)},"%m":h=>f(h.Ka+1,2),"%M":h=>f(h.Eb,2),"%n":()=>"\n","%p":h=>0<=h.Ja&&12>h.Ja?"AM":"PM","%S":h=>f(h.Fb,2),"%t":()=>"\t","%u":h=>h.na||7,"%U":h=>f(Math.floor((h.xa+
7-h.na)/7),2),"%V":h=>{var p=Math.floor((h.xa+7-(h.na+6)%7)/7);2>=(h.na+371-h.xa-2)%7&&p++;if(p)53==p&&(r=(h.na+371-h.xa)%7,4==r||3==r&&Uc(h.ya)||(p=1));else{p=52;var r=(h.na+7-h.xa-1)%7;(4==r||5==r&&Uc(h.ya%400-1))&&p++}return f(p,2)},"%w":h=>h.na,"%W":h=>f(Math.floor((h.xa+7-(h.na+6)%7)/7),2),"%y":h=>(h.ya+1900).toString().substring(2),"%Y":h=>h.ya+1900,"%z":h=>{h=h.Db;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.Gb,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(m in n)c.includes(m)&&(c=c.replace(new RegExp(m,"g"),n[m](d)));c=c.replace(/\0\0/g,"%");m=mb(c,!1);if(m.length>b)return 0;Xc(m,a);return m.length-1},$c=(a,b,c,d)=>{var e={string:n=>{var m=0;if(null!==n&&void 0!==n&&0!==n){m=kb(n)+1;var t=ic(m);lb(n,aa(),t,m);m=t}return m},array:n=>{var m=ic(n.length);g().set(n,m);return m}};a=z["_"+a];var f=[],k=0;if(d)for(var v=0;v<d.length;v++){var x=e[c[v]];x?(0===k&&(k=fc()),f[v]=x(d[v])):f[v]=d[v]}c=a.apply(null,f);return c=function(n){0!==k&&
gc(k);return"string"===b?N(n):"boolean"===b?!!n:n}(c)};O.Ea();function Mb(a,b,c,d){a||=this;this.parent=a;this.oa=a.oa;this.Ba=null;this.id=Hb++;this.name=b;this.mode=c;this.ea={};this.fa={};this.Ha=d}
Object.defineProperties(Mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},xb:{get:function(){return 16384===(this.mode&61440)}},wb:{get:function(){return 8192===(this.mode&61440)}}});Ga();S=Array(4096);Sb(R,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");pb(259,{read:()=>0,write:(d,e,f,k)=>k});Ub("/dev/null",259);ob(1280,rb);ob(1536,sb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=fb(a).byteLength);return a[--b]};J("/dev","random",c);J("/dev","urandom",c);V("/dev/shm");V("/dev/shm/tmp")})();
(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");Sb({oa(){var b=vb(a,"fd",16895,73);b.ea={Aa(c,d){var e=U(+d);c={parent:null,oa:{cb:"fake"},ea:{Ca:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();z.FS_createPath=ac;z.FS_createDataFile=Bb;z.FS_createPreloadedFile=Cb;z.FS_unlink=Vb;z.FS_createLazyFile=dc;z.FS_createDevice=J;
var ad=[kc,mc,Bc,Dc,Fc,Gc,Oc,Pc,Qc,Rc,Sc,Tc],cd={d:(a,b,c)=>{(new yc(a)).Ea(b,c);zc=a;Ac++;throw zc;},l:a=>{bd(a,!A,1,!oa,65536,!1);O.kb()},j:a=>{D?postMessage({cmd:"cleanupThread",thread:a}):O.hb(O.ma[a])},B:Cc,h:Dc,v:Fc,x:Gc,w:a=>{do{var b=y()[a>>2];a+=4;var c=y()[a>>2];a+=4;var d=y()[a>>2];a+=4;b=N(b);ac("/",cb(b),!0,!0);Bb(b,null,g().subarray(d,d+c),!0,!0,!0)}while(y()[a>>2])},n:()=>!0,z:(a,b)=>{a==b?setTimeout(()=>tc()):D?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=O.ma[a])&&a.postMessage({cmd:"checkMailbox"})},
m:(a,b,c,d)=>{Jc.length=c;d>>=3;for(var e=0;e<c;e++)Jc[e]=ha()[d+e];a=0>a?Wa[-a-1]:ad[a];O.qb=b;b=a.apply(null,Jc);O.qb=0;return b},k:Hc,D:()=>{},c:()=>{H("")},e:(a,b,c)=>{Kc.length=0;for(var d;d=aa()[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Kc.push(112==d?y()[c>>2]:105==d?w()[c>>2]:ha()[c>>3]);c+=e?8:4}return D?Y.apply(null,[-1-a,1].concat(Kc)):Wa[a].apply(null,Kc)},f:()=>{},o:()=>Date.now(),C:()=>{ab+=1;throw"unwind";},b:()=>performance.timeOrigin+performance.now(),y:a=>{var b=aa().length;a>>>=
0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-l.buffer.byteLength+65535)/65536;try{l.grow(e);u();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},s:Oc,t:Pc,A:nc,g:Qc,u:Rc,p:Sc,i:Tc,q:(a,b)=>{fb(aa().subarray(a,a+b));return 0},a:l||z.wasmMemory,r:(a,b,c,d)=>Zc(a,b,c,d)},Z=function(){function a(c,d){Z=c.exports;O.lb.push(Z.S);wc=Z.R;Ba.unshift(Z.E);wa=d;Oa("wasm-instantiate");
return Z}var b={a:cd};Na("wasm-instantiate");if(z.instantiateWasm)try{return z.instantiateWasm(b,a)}catch(c){G(`Module.instantiateWasm callback failed with error: ${c}`),ka(c)}Ta(b,function(c){a(c.instance,c.module)}).catch(ka);return{}}();z._init=()=>(z._init=Z.F)();z._move=(a,b,c,d,e)=>(z._move=Z.G)(a,b,c,d,e);z._parseandmove=a=>(z._parseandmove=Z.H)(a);z._unmove=()=>(z._unmove=Z.I)();z._listPieces=()=>(z._listPieces=Z.J)();z._getMoves=()=>(z._getMoves=Z.K)();z._getAttacks=()=>(z._getAttacks=Z.L)();
z._eval=()=>(z._eval=Z.M)();z._getBestMove=a=>(z._getBestMove=Z.N)(a);z._setFen=a=>(z._setFen=Z.O)(a);z._runPerft=(a,b)=>(z._runPerft=Z.P)(a,b);var dd=z._main=(a,b)=>(dd=z._main=Z.Q)(a,b);z.__emscripten_tls_init=()=>(z.__emscripten_tls_init=Z.S)();var sc=z._pthread_self=()=>(sc=z._pthread_self=Z.T)(),Ec=()=>(Ec=Z.U)(),bd=z.__emscripten_thread_init=(a,b,c,d,e,f)=>(bd=z.__emscripten_thread_init=Z.V)(a,b,c,d,e,f);z.__emscripten_thread_crashed=()=>(z.__emscripten_thread_crashed=Z.W)();
var jc=(a,b,c,d)=>(jc=Z.X)(a,b,c,d),rc=a=>(rc=Z.Y)(a),xc=z.__emscripten_thread_exit=a=>(xc=z.__emscripten_thread_exit=Z.Z)(a),Ic=()=>(Ic=Z._)(),uc=(a,b)=>(uc=Z.$)(a,b),fc=()=>(fc=Z.aa)(),gc=a=>(gc=Z.ba)(a),ic=a=>(ic=Z.ca)(a);z.___emscripten_embedded_file_data=448556;z.addRunDependency=Na;z.removeRunDependency=Oa;z.FS_createPath=ac;z.FS_createLazyFile=dc;z.FS_createDevice=J;z.wasmMemory=l;z.keepRuntimeAlive=()=>lc||0<ab;z.ccall=$c;
z.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?z["_"+a]:function(){return $c(a,b,c,arguments,d)}};z.ExitStatus=Xa;z.FS_createPreloadedFile=Cb;z.FS_createDataFile=Bb;z.FS_unlink=Vb;z.PThread=O;var ed;Ma=function fd(){ed||gd();ed||(Ma=fd)};
function gd(){function a(){if(!ed&&(ed=!0,z.calledRun=!0,!xa)){Ea();D||Ka(Ca);ja(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();if(hd){var b=dd;try{var c=b(0,0);nc(c,!0)}catch(d){oc(d)}}if(!D){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;)b=z.postRun.shift(),Da.unshift(b);Ka(Da)}}}if(!(0<K))if(D)ja(z),Ea(),startWorker(z);else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Aa.unshift(z.preRun.shift());Ka(Aa);0<K||
(z.setStatus?(z.setStatus("Running..."),setTimeout(function(){setTimeout(function(){z.setStatus("")},1);a()},1)):a())}}if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();var hd=!0;z.noInitialRun&&(hd=!1);gd();


  return moduleArg.ready
}
);
})();
;
export default Engine;