
var Engine = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(moduleArg = {}) {

function f(){l.buffer!=n.buffer&&p();return n}function r(){l.buffer!=n.buffer&&p();return aa}function w(){l.buffer!=n.buffer&&p();return ba}function x(){l.buffer!=n.buffer&&p();return ca}function da(){l.buffer!=n.buffer&&p();return ea}var y=moduleArg,fa,ha;y.ready=new Promise((a,b)=>{fa=a;ha=b});
var ia=Object.assign({},y),ja="./this.program",ka=(a,b)=>{throw b;},la="object"==typeof window,A="function"==typeof importScripts,ma="object"==typeof process&&"object"==typeof process.sb&&"string"==typeof process.sb.node,D=y.ENVIRONMENT_IS_PTHREAD||!1,E="";function na(a){return y.locateFile?y.locateFile(a,E):E+a}var oa;
if(la||A)A?E=self.location.href:"undefined"!=typeof document&&document.currentScript&&(E=document.currentScript.src),_scriptDir&&(E=_scriptDir),0!==E.indexOf("blob:")?E=E.substr(0,E.replace(/[?#].*/,"").lastIndexOf("/")+1):E="",A&&(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var pa=y.print||console.log.bind(console),F=y.printErr||console.error.bind(console);Object.assign(y,ia);ia=null;y.thisProgram&&(ja=y.thisProgram);
y.quit&&(ka=y.quit);var G;y.wasmBinary&&(G=y.wasmBinary);"object"!=typeof WebAssembly&&H("no native wasm support detected");var l,qa,ra=!1,K,n,aa,ba,ca,ea;function p(){var a=l.buffer;y.HEAP8=n=new Int8Array(a);y.HEAP16=new Int16Array(a);y.HEAPU8=aa=new Uint8Array(a);y.HEAPU16=new Uint16Array(a);y.HEAP32=ba=new Int32Array(a);y.HEAPU32=ca=new Uint32Array(a);y.HEAPF32=new Float32Array(a);y.HEAPF64=ea=new Float64Array(a)}var sa=y.INITIAL_MEMORY||629145600;
65536<=sa||H("INITIAL_MEMORY should be larger than STACK_SIZE, was "+sa+"! (STACK_SIZE=65536)");
if(D)l=y.wasmMemory;else if(y.wasmMemory)l=y.wasmMemory;else if(l=new WebAssembly.Memory({initial:sa/65536,maximum:32768,shared:!0}),!(l.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ma&&F("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");p();sa=l.buffer.byteLength;var ta=[],ua=[],va=[],wa=[];function xa(){D||(y.noFSInit||ya||(ya=!0,za(),y.stdin=y.stdin,y.stdout=y.stdout,y.stderr=y.stderr,y.stdin?L("stdin",y.stdin):Aa("/dev/tty","/dev/stdin"),y.stdout?L("stdout",null,y.stdout):Aa("/dev/tty","/dev/stdout"),y.stderr?L("stderr",null,y.stderr):Aa("/dev/tty1","/dev/stderr"),Ba("/dev/stdin",0),Ba("/dev/stdout",1),Ba("/dev/stderr",1)),Ca=!1,Da(ua))}var M=0,Ea=null,N=null;
function Fa(){M++;y.monitorRunDependencies&&y.monitorRunDependencies(M)}function Ga(){M--;y.monitorRunDependencies&&y.monitorRunDependencies(M);if(0==M&&(null!==Ea&&(clearInterval(Ea),Ea=null),N)){var a=N;N=null;a()}}function H(a){if(y.onAbort)y.onAbort(a);a="Aborted("+a+")";F(a);ra=!0;K=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha(a);throw a;}var Ha=a=>a.startsWith("data:application/octet-stream;base64,"),O;
y.locateFile?(O="ChessEngine.wasm",Ha(O)||(O=na(O))):O=(new URL("ChessEngine.wasm",import.meta.url)).href;function Ia(a){if(a==O&&G)return new Uint8Array(G);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}function Ja(a){return G||!la&&!A||"function"!=typeof fetch?Promise.resolve().then(()=>Ia(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ia(a))}
function Ka(a,b,c){return Ja(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{F(`failed to asynchronously prepare wasm: ${d}`);H(d)})}function La(a,b){var c=O;return G||"function"!=typeof WebAssembly.instantiateStreaming||Ha(c)||"function"!=typeof fetch?Ka(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){F(`wasm streaming compile failed: ${e}`);F("falling back to ArrayBuffer instantiation");return Ka(c,a,b)}))}
var P,Ma,Na={155016:a=>{postMessage({data:[R(a)],name:"log"})},155068:(a,b)=>{postMessage({data:[R(b)],name:R(a)})},155131:(a,b)=>{postMessage({data:[b],name:R(a)})}};function Oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Pa=a=>{a.terminate();a.onmessage=()=>{}},Ra=a=>{0==S.la.length&&(Qa(),S.Pa(S.la[0]));var b=S.la.pop();if(!b)return 6;S.oa.push(b);S.ga[a.na]=b;b.na=a.na;b.postMessage({cmd:"run",start_routine:a.kb,arg:a.bb,pthread_ptr:a.na},a.qb);return 0},T=0,Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(d=>
!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Va=a=>{if("/"===a)return"/";a=Ta(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Wa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);H("initRandomDevice")},
Xa=a=>(Xa=Wa())(a);function Ya(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,$a=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Za)return Za.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,d):a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else c+=String.fromCharCode(e)}return c},ab=[],bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},cb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var v=a.charCodeAt(++h);k=65536+((k&1023)<<10)|v&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+
3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e};function db(a,b){var c=Array(bb(a)+1);a=cb(a,c,0,c.length);b&&(c.length=a);return c}var eb=[];function fb(a,b){eb[a]={input:[],da:[],ta:b};gb(a,hb)}
var hb={open(a){var b=eb[a.node.Ba];if(!b)throw new U(43);a.ea=b;a.seekable=!1},close(a){a.ea.ta.xa(a.ea)},xa(a){a.ea.ta.xa(a.ea)},read(a,b,c,d){if(!a.ea||!a.ea.ta.Oa)throw new U(60);for(var e=0,h=0;h<d;h++){try{var k=a.ea.ta.Oa(a.ea)}catch(v){throw new U(29);}if(void 0===k&&0===e)throw new U(6);if(null===k||void 0===k)break;e++;b[c+h]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.ea||!a.ea.ta.Ha)throw new U(60);try{for(var e=0;e<d;e++)a.ea.ta.Ha(a.ea,b[c+e])}catch(h){throw new U(29);
}d&&(a.node.timestamp=Date.now());return e}},ib={Oa(){a:{if(!ab.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}ab=db(a,!0)}a=ab.shift()}return a},Ha(a,b){null===b||10===b?(pa($a(a.da,0)),a.da=[]):0!=b&&a.da.push(b)},xa(a){a.da&&0<a.da.length&&(pa($a(a.da,0)),a.da=[])},Ib(){return{zb:25856,Bb:5,yb:191,Ab:35387,xb:[3,28,127,21,4,0,1,
0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Jb(){return 0},Kb(){return[24,80]}},jb={Ha(a,b){null===b||10===b?(F($a(a.da,0)),a.da=[]):0!=b&&a.da.push(b)},xa(a){a.da&&0<a.da.length&&(F($a(a.da,0)),a.da=[])}};function kb(a,b){var c=a.$?a.$.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.$,a.$=new Uint8Array(b),0<a.ca&&a.$.set(c.subarray(0,a.ca),0))}
var V={fa:null,ja(){return V.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new U(63);V.fa||(V.fa={dir:{node:{ka:V.aa.ka,ha:V.aa.ha,ua:V.aa.ua,ya:V.aa.ya,Ua:V.aa.Ua,$a:V.aa.$a,Wa:V.aa.Wa,Ta:V.aa.Ta,Ca:V.aa.Ca},stream:{ma:V.ba.ma}},file:{node:{ka:V.aa.ka,ha:V.aa.ha},stream:{ma:V.ba.ma,read:V.ba.read,write:V.ba.write,Ka:V.ba.Ka,Qa:V.ba.Qa,Sa:V.ba.Sa}},link:{node:{ka:V.aa.ka,ha:V.aa.ha,va:V.aa.va},stream:{}},La:{node:{ka:V.aa.ka,ha:V.aa.ha},stream:lb}});
c=mb(a,b,c,d);16384===(c.mode&61440)?(c.aa=V.fa.dir.node,c.ba=V.fa.dir.stream,c.$={}):32768===(c.mode&61440)?(c.aa=V.fa.file.node,c.ba=V.fa.file.stream,c.ca=0,c.$=null):40960===(c.mode&61440)?(c.aa=V.fa.link.node,c.ba=V.fa.link.stream):8192===(c.mode&61440)&&(c.aa=V.fa.La.node,c.ba=V.fa.La.stream);c.timestamp=Date.now();a&&(a.$[b]=c,a.timestamp=c.timestamp);return c},Fb(a){return a.$?a.$.subarray?a.$.subarray(0,a.ca):new Uint8Array(a.$):new Uint8Array(0)},aa:{ka(a){var b={};b.Eb=8192===(a.mode&61440)?
a.id:1;b.Hb=a.id;b.mode=a.mode;b.Mb=1;b.uid=0;b.Gb=0;b.Ba=a.Ba;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ca:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.vb=new Date(a.timestamp);b.Lb=new Date(a.timestamp);b.Db=new Date(a.timestamp);b.eb=4096;b.wb=Math.ceil(b.size/b.eb);return b},ha(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ca!=b))if(0==b)a.$=null,a.ca=0;else{var c=a.$;a.$=new Uint8Array(b);
c&&a.$.set(c.subarray(0,Math.min(b,a.ca)));a.ca=b}},ua(){throw nb[44];},ya(a,b,c,d){return V.createNode(a,b,c,d)},Ua(a,b,c){if(16384===(a.mode&61440)){try{var d=ob(b,c)}catch(h){}if(d)for(var e in d.$)throw new U(55);}delete a.parent.$[a.name];a.parent.timestamp=Date.now();a.name=c;b.$[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},$a(a,b){delete a.$[b];a.timestamp=Date.now()},Wa(a,b){var c=ob(a,b),d;for(d in c.$)throw new U(55);delete a.$[b];a.timestamp=Date.now()},Ta(a){var b=[".",".."],c;for(c in a.$)a.$.hasOwnProperty(c)&&
b.push(c);return b},Ca(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},va(a){if(40960!==(a.mode&61440))throw new U(28);return a.link}},ba:{read(a,b,c,d,e){var h=a.node.$;if(e>=a.node.ca)return 0;a=Math.min(a.node.ca-e,d);if(8<a&&h.subarray)b.set(h.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=h[e+d];return a},write(a,b,c,d,e,h){b.buffer===f().buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.$||a.$.subarray)){if(h)return a.$=b.subarray(c,c+d),a.ca=d;if(0===a.ca&&
0===e)return a.$=b.slice(c,c+d),a.ca=d;if(e+d<=a.ca)return a.$.set(b.subarray(c,c+d),e),d}kb(a,e+d);if(a.$.subarray&&b.subarray)a.$.set(b.subarray(c,c+d),e);else for(h=0;h<d;h++)a.$[e+h]=b[c+h];a.ca=Math.max(a.ca,e+d);return d},ma(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ca);if(0>b)throw new U(28);return b},Ka(a,b,c){kb(a.node,b+c);a.node.ca=Math.max(a.node.ca,b+c)},Qa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new U(43);a=a.node.$;if(e&2||a.buffer!==f().buffer){if(0<
c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;H();b=void 0;if(!b)throw new U(48);f().set(a,b)}else c=!1,b=a.byteOffset;return{Aa:b,ub:c}},Sa(a,b,c,d){V.ba.write(a,b,0,d,c,!1);return 0}}},pb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qb=null,rb={},sb=[],tb=1,ub=null,Ca=!0,U=null,nb={};
function W(a,b={}){a=Ya(a);if(!a)return{path:"",node:null};b=Object.assign({Na:!0,Ia:0},b);if(8<b.Ia)throw new U(32);a=a.split("/").filter(k=>!!k);for(var c=qb,d="/",e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;c=ob(c,a[e]);d=Ta(d+"/"+a[e]);c.za&&(!h||h&&b.Na)&&(c=c.za.root);if(!h||b.Ma)for(h=0;40960===(c.mode&61440);)if(c=vb(d),d=Ya(Ua(d),c),c=W(d,{Ia:b.Ia+1}).node,40<h++)throw new U(32);}return{path:d,node:c}}
function wb(a){for(var b;;){if(a===a.parent)return a=a.ja.Ra,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ub.length}function ob(a,b){var c;if(c=(c=yb(a,"x"))?c:a.aa.ua?0:2)throw new U(c,a);for(c=ub[xb(a.id,b)];c;c=c.hb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.aa.ua(a,b)}
function mb(a,b,c,d){a=new zb(a,b,c,d);b=xb(a.parent.id,a.name);a.hb=ub[b];return ub[b]=a}function Ab(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(Ca)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Bb(a,b){try{return ob(a,b),20}catch(c){}return yb(a,"wx")}function Cb(){for(var a=0;4096>=a;a++)if(!sb[a])return a;throw new U(33);}
function Db(a){a=sb[a];if(!a)throw new U(8);return a}function Eb(a){var b=-1;Fb||(Fb=function(){this.ra={}},Fb.prototype={},Object.defineProperties(Fb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ra.flags},set(c){this.ra.flags=c}},position:{get(){return this.ra.position},set(c){this.ra.position=c}}}));a=Object.assign(new Fb,a);-1==b&&(b=Cb());a.sa=b;return sb[b]=a}var lb={open(a){a.ba=rb[a.node.Ba].ba;a.ba.open&&a.ba.open(a)},ma(){throw new U(70);}};
function gb(a,b){rb[a]={ba:b}}function Gb(a,b){var c="/"===b,d=!b;if(c&&qb)throw new U(10);if(!c&&!d){var e=W(b,{Na:!1});b=e.path;e=e.node;if(e.za)throw new U(10);if(16384!==(e.mode&61440))throw new U(54);}b={type:a,Nb:{},Ra:b,gb:[]};a=a.ja(b);a.ja=b;b.root=a;c?qb=a:e&&(e.za=b,e.ja&&e.ja.gb.push(b))}function Hb(a,b,c){var d=W(a,{parent:!0}).node;a=Va(a);if(!a||"."===a||".."===a)throw new U(28);var e=Bb(d,a);if(e)throw new U(e);if(!d.aa.ya)throw new U(63);return d.aa.ya(d,a,b,c)}
function X(a){return Hb(a,16895,0)}function Ib(a,b,c){"undefined"==typeof c&&(c=b,b=438);Hb(a,b|8192,c)}function Aa(a,b){if(!Ya(a))throw new U(44);var c=W(b,{parent:!0}).node;if(!c)throw new U(44);b=Va(b);var d=Bb(c,b);if(d)throw new U(d);if(!c.aa.Ca)throw new U(63);c.aa.Ca(c,b,a)}function vb(a){a=W(a).node;if(!a)throw new U(44);if(!a.aa.va)throw new U(28);return Ya(wb(a.parent),a.aa.va(a))}
function Ba(a,b){if(""===a)throw new U(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}var d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ta(a);try{e=W(a,{Ma:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new U(20);}else e=Hb(a,d,0),c=!0;if(!e)throw new U(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new U(54);
if(!c&&(d=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ab(b)||b&512)?31:yb(e,Ab(b)):44))throw new U(d);if(b&512&&!c){d=e;d="string"==typeof d?W(d,{Ma:!0}).node:d;if(!d.aa.ha)throw new U(63);if(16384===(d.mode&61440))throw new U(31);if(32768!==(d.mode&61440))throw new U(28);if(c=yb(d,"w"))throw new U(c);d.aa.ha(d,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:e,path:wb(e),flags:b,seekable:!0,position:0,ba:e.ba,rb:[],error:!1});e.ba.open&&e.ba.open(e);!y.logReadFiles||b&1||(Jb||=
{},a in Jb||(Jb[a]=1))}function Kb(a,b,c){if(null===a.sa)throw new U(8);if(!a.seekable||!a.ba.ma)throw new U(70);if(0!=c&&1!=c&&2!=c)throw new U(28);a.position=a.ba.ma(a,b,c);a.rb=[]}function za(){U||(U=function(a,b){this.name="ErrnoError";this.node=b;this.jb=function(c){this.wa=c};this.jb(a);this.message="FS error"},U.prototype=Error(),U.prototype.constructor=U,[44].forEach(a=>{nb[a]=new U(a);nb[a].stack="<generic error, no stack>"}))}var ya;
function L(a,b,c){a=Ta("/dev/"+a);var d=pb(!!b,!!c);Lb||=64;var e=Lb++<<8|0;gb(e,{open(h){h.seekable=!1},close(){c&&c.buffer&&c.buffer.length&&c(10)},read(h,k,v,B){for(var m=0,t=0;t<B;t++){try{var C=b()}catch(I){throw new U(29);}if(void 0===C&&0===m)throw new U(6);if(null===C||void 0===C)break;m++;k[v+t]=C}m&&(h.node.timestamp=Date.now());return m},write(h,k,v,B){for(var m=0;m<B;m++)try{c(k[v+m])}catch(t){throw new U(29);}B&&(h.node.timestamp=Date.now());return m}});Ib(a,d,e)}
var Lb,Mb={},Fb,Jb,R=a=>a?$a(r(),a):"",Pb=a=>{var b=Nb();a=a();Ob(b);return a};function Y(a,b){var c=arguments.length-2,d=arguments;return Pb(()=>{for(var e=Qb(8*c),h=e>>3,k=0;k<c;k++){var v=d[2+k];da()[h+k]=v}return Rb(a,c,e,b)})}function Sb(a){if(D)return Y(0,1,a);K=a;if(!(Tb||0<T)){S.lb();if(y.onExit)y.onExit(a);ra=!0}ka(a,new Oa(a))}var Vb=a=>{K=a;if(D)throw Ub(a),"unwind";Sb(a)},Wb=a=>{a instanceof Oa||"unwind"==a||ka(1,a)};
function Xb(){for(var a=8;a--;)Qa();ta.unshift(()=>{Fa();Yb(()=>Ga())})}function Qa(){if(y.locateFile){var a=na("ChessEngine.worker.js");a=new Worker(a,{type:"module"})}else a=new Worker(new URL("ChessEngine.worker.js",import.meta.url),{type:"module"});S.la.push(a)}function Yb(a){D?a():Promise.all(S.la.map(S.Pa)).then(a)}
var S={la:[],oa:[],Za:[],ga:{},Ga(){D?(S.receiveObjectTransfer=S.ib,S.threadInitTLS=S.Ya,S.setExitStatus=S.Xa,Tb=!1):Xb()},Xa:a=>{K=a},Ob:["$terminateWorker"],lb:()=>{for(var a of S.oa)Pa(a);for(a of S.la)Pa(a);S.la=[];S.oa=[];S.ga=[]},Va:a=>{var b=a.na;delete S.ga[b];S.la.push(a);S.oa.splice(S.oa.indexOf(a),1);a.na=0;Zb(b)},ib(){},Ya(){S.Za.forEach(a=>a())},Pa:a=>new Promise(b=>{a.onmessage=h=>{h=h.data;var k=h.cmd;if(h.targetThread&&h.targetThread!=$b()){var v=S.ga[h.targetThread];v?v.postMessage(h,
h.transferList):F(`Internal error! Worker sent a message "${k}" to target pthread ${h.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===k)ac();else if("spawnThread"===k)Ra(h);else if("cleanupThread"===k)S.Va(S.ga[h.thread]);else if("killThread"===k)h=h.thread,k=S.ga[h],delete S.ga[h],Pa(k),Zb(h),S.oa.splice(S.oa.indexOf(k),1),k.na=0;else if("cancelThread"===k)S.ga[h.thread].postMessage({cmd:"cancel"});else if("loaded"===k)a.loaded=!0,b(a);else if("alert"===k)alert(`Thread ${h.threadId}: ${h.text}`);
else if("setimmediate"===h.target)a.postMessage(h);else if("callHandler"===k)y[h.handler](...h.args);else k&&F(`worker sent an unknown command ${k}`)};a.onerror=h=>{F(`${"worker sent an error!"} ${h.filename}:${h.lineno}: ${h.message}`);throw h;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)y.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:y.mainScriptUrlOrBlob,wasmMemory:l,wasmModule:qa})})};y.PThread=S;var Da=a=>{for(;0<a.length;)a.shift()(y)};
y.establishStackSpace=()=>{var a=$b(),b=x()[a+52>>2];a=x()[a+56>>2];bc(b,b-a);Ob(b)};function Ub(a){if(D)return Y(1,0,a);Vb(a)}var cc=[],dc;y.invokeEntryPoint=(a,b)=>{var c=cc[a];c||(a>=cc.length&&(cc.length=a+1),cc[a]=c=dc.get(a));a=c(b);Tb||0<T?S.Xa(a):ec(a)};var Tb=y.noExitRuntime||!0;function fc(a){this.Aa=a-24;this.cb=function(b){x()[this.Aa+4>>2]=b};this.ab=function(b){x()[this.Aa+8>>2]=b};this.Ga=function(b,c){this.ra();this.cb(b);this.ab(c)};this.ra=function(){x()[this.Aa+16>>2]=0}}
var gc=0,hc=0;function ic(a,b,c,d){return D?Y(2,1,a,b,c,d):jc(a,b,c,d)}var jc=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(D&&0===e.length)return ic(a,b,c,d);a={kb:c,na:a,bb:d,qb:e};return D?(a.Cb="spawnThread",postMessage(a,e),0):Ra(a)},kc=a=>{"function"===typeof Atomics.tb&&(Atomics.tb(w(),a>>2,a).value.then(ac),a+=128,Atomics.store(w(),a>>2,1))};
y.__emscripten_thread_mailbox_await=kc;var ac=()=>{var a=$b();if(a&&(kc(a),a=lc,!ra))try{if(a(),!(Tb||0<T))try{D?ec(K):Vb(K)}catch(b){Wb(b)}}catch(b){Wb(b)}};y.checkMailbox=ac;
var mc=[],nc=[],oc={},qc=()=>{if(!pc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ja||"./this.program"},b;for(b in oc)void 0===oc[b]?delete a[b]:a[b]=oc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);pc=c}return pc},pc;
function rc(a,b){if(D)return Y(3,1,a,b);var c=0;qc().forEach((d,e)=>{var h=b+c;e=x()[a+4*e>>2]=h;for(h=0;h<d.length;++h)f()[e++>>0]=d.charCodeAt(h);f()[e>>0]=0;c+=d.length+1});return 0}function sc(a,b){if(D)return Y(4,1,a,b);var c=qc();x()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x()[b>>2]=d;return 0}
function tc(a){if(D)return Y(5,1,a);try{var b=Db(a);if(null===b.sa)throw new U(8);b.Fa&&(b.Fa=null);try{b.ba.close&&b.ba.close(b)}catch(c){throw c;}finally{sb[b.sa]=null}b.sa=null;return 0}catch(c){if("undefined"==typeof Mb||"ErrnoError"!==c.name)throw c;return c.wa}}
function uc(a,b,c,d){if(D)return Y(6,1,a,b,c,d);try{a:{var e=Db(a);a=b;for(var h,k=b=0;k<c;k++){var v=x()[a>>2],B=x()[a+4>>2];a+=8;var m=e,t=f(),C=v,I=B,g=h;if(0>I||0>g)throw new U(28);if(null===m.sa)throw new U(8);if(1===(m.flags&2097155))throw new U(8);if(16384===(m.node.mode&61440))throw new U(31);if(!m.ba.read)throw new U(28);var q="undefined"!=typeof g;if(!q)g=m.position;else if(!m.seekable)throw new U(70);var u=m.ba.read(m,t,C,I,g);q||(m.position+=u);var z=u;if(0>z){var J=-1;break a}b+=z;if(z<
B)break;"undefined"!==typeof h&&(h+=z)}J=b}x()[d>>2]=J;return 0}catch(Q){if("undefined"==typeof Mb||"ErrnoError"!==Q.name)throw Q;return Q.wa}}
function vc(a,b,c,d,e){if(D)return Y(7,1,a,b,c,d,e);b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var h=Db(a);Kb(h,b,d);Ma=[h.position>>>0,(P=h.position,1<=+Math.abs(P)?0<P?+Math.floor(P/4294967296)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];w()[e>>2]=Ma[0];w()[e+4>>2]=Ma[1];h.Fa&&0===b&&0===d&&(h.Fa=null);return 0}catch(k){if("undefined"==typeof Mb||"ErrnoError"!==k.name)throw k;return k.wa}}
function wc(a,b,c,d){if(D)return Y(8,1,a,b,c,d);try{a:{var e=Db(a);a=b;for(var h,k=b=0;k<c;k++){var v=x()[a>>2],B=x()[a+4>>2];a+=8;var m=e,t=f(),C=v,I=B,g=h;if(0>I||0>g)throw new U(28);if(null===m.sa)throw new U(8);if(0===(m.flags&2097155))throw new U(8);if(16384===(m.node.mode&61440))throw new U(31);if(!m.ba.write)throw new U(28);m.seekable&&m.flags&1024&&Kb(m,0,2);var q="undefined"!=typeof g;if(!q)g=m.position;else if(!m.seekable)throw new U(70);var u=m.ba.write(m,t,C,I,g,void 0);q||(m.position+=
u);var z=u;if(0>z){var J=-1;break a}b+=z;"undefined"!==typeof h&&(h+=z)}J=b}x()[d>>2]=J;return 0}catch(Q){if("undefined"==typeof Mb||"ErrnoError"!==Q.name)throw Q;return Q.wa}}
var xc=a=>0===a%4&&(0!==a%100||0===a%400),yc=[31,29,31,30,31,30,31,31,30,31,30,31],zc=[31,28,31,30,31,30,31,31,30,31,30,31],Ac=(a,b)=>{f().set(a,b)},Bc=(a,b,c,d)=>{function e(g,q,u){for(g="number"==typeof g?g.toString():g||"";g.length<q;)g=u[0]+g;return g}function h(g,q){return e(g,q,"0")}function k(g,q){function u(J){return 0>J?-1:0<J?1:0}var z;0===(z=u(g.getFullYear()-q.getFullYear()))&&0===(z=u(g.getMonth()-q.getMonth()))&&(z=u(g.getDate()-q.getDate()));return z}function v(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-
1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function B(g){var q=g.pa;for(g=new Date((new Date(g.qa+1900,0,1)).getTime());0<q;){var u=g.getMonth(),z=(xc(g.getFullYear())?yc:zc)[u];if(q>z-g.getDate())q-=z-g.getDate()+1,g.setDate(1),11>u?g.setMonth(u+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+
1));else{g.setDate(g.getDate()+q);break}}u=new Date(g.getFullYear()+1,0,4);q=v(new Date(g.getFullYear(),0,4));u=v(u);return 0>=k(q,g)?0>=k(u,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var m=x()[d+40>>2];d={ob:w()[d>>2],nb:w()[d+4>>2],Da:w()[d+8>>2],Ja:w()[d+12>>2],Ea:w()[d+16>>2],qa:w()[d+20>>2],ia:w()[d+24>>2],pa:w()[d+28>>2],Pb:w()[d+32>>2],mb:w()[d+36>>2],pb:m?R(m):""};c=R(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in m)c=c.replace(new RegExp(t,"g"),m[t]);var C="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),I="January February March April May June July August September October November December".split(" ");m={"%a":g=>C[g.ia].substring(0,
3),"%A":g=>C[g.ia],"%b":g=>I[g.Ea].substring(0,3),"%B":g=>I[g.Ea],"%C":g=>h((g.qa+1900)/100|0,2),"%d":g=>h(g.Ja,2),"%e":g=>e(g.Ja,2," "),"%g":g=>B(g).toString().substring(2),"%G":g=>B(g),"%H":g=>h(g.Da,2),"%I":g=>{g=g.Da;0==g?g=12:12<g&&(g-=12);return h(g,2)},"%j":g=>{for(var q=0,u=0;u<=g.Ea-1;q+=(xc(g.qa+1900)?yc:zc)[u++]);return h(g.Ja+q,3)},"%m":g=>h(g.Ea+1,2),"%M":g=>h(g.nb,2),"%n":()=>"\n","%p":g=>0<=g.Da&&12>g.Da?"AM":"PM","%S":g=>h(g.ob,2),"%t":()=>"\t","%u":g=>g.ia||7,"%U":g=>h(Math.floor((g.pa+
7-g.ia)/7),2),"%V":g=>{var q=Math.floor((g.pa+7-(g.ia+6)%7)/7);2>=(g.ia+371-g.pa-2)%7&&q++;if(q)53==q&&(u=(g.ia+371-g.pa)%7,4==u||3==u&&xc(g.qa)||(q=1));else{q=52;var u=(g.ia+7-g.pa-1)%7;(4==u||5==u&&xc(g.qa%400-1))&&q++}return h(q,2)},"%w":g=>g.ia,"%W":g=>h(Math.floor((g.pa+7-(g.ia+6)%7)/7),2),"%y":g=>(g.qa+1900).toString().substring(2),"%Y":g=>g.qa+1900,"%z":g=>{g=g.mb;var q=0<=g;g=Math.abs(g)/60;return(q?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":g=>g.pb,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(t in m)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),m[t](d)));c=c.replace(/\0\0/g,"%");t=db(c,!1);if(t.length>b)return 0;Ac(t,a);return t.length-1},Cc=(a,b,c,d)=>{var e={string:m=>{var t=0;if(null!==m&&void 0!==m&&0!==m){t=bb(m)+1;var C=Qb(t);cb(m,r(),C,t);t=C}return t},array:m=>{var t=Qb(m.length);f().set(m,t);return t}};a=y["_"+a];var h=[],k=0;if(d)for(var v=0;v<d.length;v++){var B=e[c[v]];B?(0===k&&(k=Nb()),h[v]=B(d[v])):h[v]=d[v]}c=a.apply(null,h);return c=function(m){0!==k&&
Ob(k);return"string"===b?R(m):"boolean"===b?!!m:m}(c)};S.Ga();function zb(a,b,c,d){a||=this;this.parent=a;this.ja=a.ja;this.za=null;this.id=tb++;this.name=b;this.mode=c;this.aa={};this.ba={};this.Ba=d}Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});za();ub=Array(4096);Gb(V,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");gb(259,{read:()=>0,write:(d,e,h,k)=>k});Ib("/dev/null",259);fb(1280,ib);fb(1536,jb);Ib("/dev/tty",1280);Ib("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Xa(a).byteLength);return a[--b]};L("random",c);L("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Gb({ja(){var b=mb(a,"fd",16895,73);b.aa={ua(c,d){var e=Db(+d);c={parent:null,ja:{Ra:"fake"},aa:{va:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Dc=[Sb,Ub,ic,rc,sc,tc,uc,vc,wc],Fc={d:(a,b,c)=>{(new fc(a)).Ga(b,c);gc=a;hc++;throw gc;},k:a=>{Ec(a,!A,1,!la,65536,!1);S.Ya()},h:a=>{D?postMessage({cmd:"cleanupThread",thread:a}):S.Va(S.ga[a])},y:jc,m:()=>!0,w:(a,b)=>{a==b?setTimeout(()=>ac()):D?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=S.ga[a])&&a.postMessage({cmd:"checkMailbox"})},l:(a,b,c,d)=>{mc.length=c;d>>=3;for(var e=0;e<c;e++)mc[e]=da()[d+e];a=0>a?Na[-a-1]:Dc[a];S.fb=b;b=a.apply(null,mc);S.fb=0;return b},j:kc,i:()=>{},c:()=>
{H("")},e:(a,b,c)=>{nc.length=0;for(var d;d=r()[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;nc.push(112==d?x()[c>>2]:105==d?w()[c>>2]:da()[c>>3]);c+=e?8:4}return D?Y.apply(null,[-1-a,1].concat(nc)):Na[a].apply(null,nc)},f:()=>{},n:()=>Date.now(),z:()=>{T+=1;throw"unwind";},b:()=>performance.timeOrigin+performance.now(),v:a=>{var b=r().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,
d+(65536-d%65536)%65536)-l.buffer.byteLength+65535)/65536;try{l.grow(e);p();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},r:rc,s:sc,x:Vb,t:tc,u:uc,o:vc,g:wc,p:(a,b)=>{Xa(r().subarray(a,a+b));return 0},a:l||y.wasmMemory,q:(a,b,c,d)=>Bc(a,b,c,d)},Z=function(){function a(c,d){Z=c.exports;S.Za.push(Z.O);dc=Z.N;ua.unshift(Z.A);qa=d;Ga();return Z}var b={a:Fc};Fa();if(y.instantiateWasm)try{return y.instantiateWasm(b,a)}catch(c){F(`Module.instantiateWasm callback failed with error: ${c}`),ha(c)}La(b,
function(c){a(c.instance,c.module)}).catch(ha);return{}}();y._init=()=>(y._init=Z.B)();y._move=(a,b,c,d,e)=>(y._move=Z.C)(a,b,c,d,e);y._parseandmove=a=>(y._parseandmove=Z.D)(a);y._unmove=()=>(y._unmove=Z.E)();y._listPieces=()=>(y._listPieces=Z.F)();y._getMoves=()=>(y._getMoves=Z.G)();y._getAttacks=()=>(y._getAttacks=Z.H)();y._eval=()=>(y._eval=Z.I)();y._getBestMove=a=>(y._getBestMove=Z.J)(a);y._setFen=a=>(y._setFen=Z.K)(a);y._runPerft=(a,b)=>(y._runPerft=Z.L)(a,b);
var Gc=y._main=(a,b)=>(Gc=y._main=Z.M)(a,b);y.__emscripten_tls_init=()=>(y.__emscripten_tls_init=Z.O)();var $b=y._pthread_self=()=>($b=y._pthread_self=Z.P)(),Ec=y.__emscripten_thread_init=(a,b,c,d,e,h)=>(Ec=y.__emscripten_thread_init=Z.Q)(a,b,c,d,e,h);y.__emscripten_thread_crashed=()=>(y.__emscripten_thread_crashed=Z.R)();
var Rb=(a,b,c,d)=>(Rb=Z.S)(a,b,c,d),Zb=a=>(Zb=Z.T)(a),ec=y.__emscripten_thread_exit=a=>(ec=y.__emscripten_thread_exit=Z.U)(a),lc=()=>(lc=Z.V)(),bc=(a,b)=>(bc=Z.W)(a,b),Nb=()=>(Nb=Z.X)(),Ob=a=>(Ob=Z.Y)(a),Qb=a=>(Qb=Z.Z)(a);y.wasmMemory=l;y.keepRuntimeAlive=()=>Tb||0<T;y.ccall=Cc;y.cwrap=(a,b,c,d)=>{var e=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&e&&!d?y["_"+a]:function(){return Cc(a,b,c,arguments,d)}};y.ExitStatus=Oa;y.PThread=S;var Hc;N=function Ic(){Hc||Jc();Hc||(N=Ic)};
function Jc(){function a(){if(!Hc&&(Hc=!0,y.calledRun=!0,!ra)){xa();D||Da(va);fa(y);if(y.onRuntimeInitialized)y.onRuntimeInitialized();if(Kc){var b=Gc;try{var c=b(0,0);Vb(c,!0)}catch(d){Wb(d)}}if(!D){if(y.postRun)for("function"==typeof y.postRun&&(y.postRun=[y.postRun]);y.postRun.length;)b=y.postRun.shift(),wa.unshift(b);Da(wa)}}}if(!(0<M))if(D)fa(y),xa(),startWorker(y);else{if(y.preRun)for("function"==typeof y.preRun&&(y.preRun=[y.preRun]);y.preRun.length;)ta.unshift(y.preRun.shift());Da(ta);0<M||
(y.setStatus?(y.setStatus("Running..."),setTimeout(function(){setTimeout(function(){y.setStatus("")},1);a()},1)):a())}}if(y.preInit)for("function"==typeof y.preInit&&(y.preInit=[y.preInit]);0<y.preInit.length;)y.preInit.pop()();var Kc=!0;y.noInitialRun&&(Kc=!1);Jc();


  return moduleArg.ready
}
);
})();
;
export default Engine;